// Application logic and canvas commands under a minimal DOM. Not a browser/layout test.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
function boot(hash=''){
const ids=new Map(),elements=[],events={},storage=new Map(),commands=[];
class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.style={};this._value='';this.checked=false;this.hidden=false;this.attrs={};this.isConnected=true;this.selectionStart=this.selectionEnd=0;elements.push(this);}set id(v){this._id=v;ids.set(v,this);}get id(){return this._id;}set value(v){this._value=String(v);}get value(){return this._value;}get options(){return this.children;}append(...nodes){for(const n of nodes){this.children.push(n);n.parentElement=this;}if(this.tagName==='SELECT'&&this.children.length&&this._value==='')this._value=this.children[0].value;}replaceChildren(...nodes){for(const n of this.children)n.isConnected=false;this.children=[];this._value=this.tagName==='SELECT'?'':this._value;this.append(...nodes);}setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k];}focus(){}scrollIntoView(){}showModal(){this.open=true;}close(){this.open=false;}click(){this.onclick?.({});}getBoundingClientRect(){return {width:960,height:560,left:0,top:0};}getContext(){return new Proxy({},{get:(_,key)=>(...args)=>{if(['moveTo','lineTo','arc'].includes(key))assert.ok(args.slice(0,2).every(Number.isFinite));commands.push({key,args});},set:(_,key,value)=>{commands.push({key,args:[value]});return true;}});}setPointerCapture(){}setRangeText(s,a,b){this.value=this.value.slice(0,a)+s+this.value.slice(b);}setSelectionRange(a,b){this.selectionStart=a;this.selectionEnd=b;}}
for(const match of fs.readFileSync(__dirname+'/../../CurveLab/construction.html','utf8').matchAll(/<(\w+)\b([^>]*)>/g)){const [,tag,attrs]=match,e=new Element(tag),id=attrs.match(/\bid="([^"]+)"/);if(id)e.id=id[1];e.checked=/\bchecked\b/.test(attrs);e.hidden=/\bhidden\b/.test(attrs);const view=attrs.match(/data-view="([^"]+)"/);if(view)e.dataset.view=view[1];const value=attrs.match(/\bvalue="([^"]*)"/);if(value)e.value=value[1];e.parentElement=new Element('label');}
const document={getElementById:id=>ids.get(id)||null,createElement:tag=>new Element(tag),querySelectorAll:sel=>sel==='[data-view]'?elements.filter(e=>e.dataset.view):[],querySelector:sel=>sel==='[data-math]'?elements.find(e=>Object.hasOwn(e.dataset,'math')&&e.isConnected):null,addEventListener:(key,fn)=>events[key]=fn};
const c={document,console,structuredClone,Math,Number,Map,Set,Array,Object,String,Error,JSON,Date,Boolean,Blob,URL,setTimeout,clearTimeout,devicePixelRatio:1,location:{hash,pathname:'/construction.html'},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},ResizeObserver:class{constructor(fn){this.fn=fn;}observe(){this.fn();}},Option:class extends Element{constructor(text,value){super('option');this.textContent=text;this.value=value;}},history:{replaceState(){}},addEventListener:(key,fn)=>events[key]=fn};c.window=c;vm.createContext(c);for(const f of ['tikz-export.js','engine.js','construction-core.js','construction-view.js','construction-specs.js','construction.js'])vm.runInContext(fs.readFileSync(__dirname+'/../../CurveLab/'+f,'utf8'),c,{filename:f});const $=id=>ids.get(id);const ev=p=>({button:0,clientX:p[0],clientY:p[1],pointerId:1,preventDefault(){}});const click=p=>{$('board').onpointerdown(ev(p));$('board').onpointerup(ev(p));};return {c,$,commands,click,ev,events};}
const t=boot(),{c,$,commands,click,ev}=t,app=c.ConstructionApp;
const find=name=>app.objects.find(o=>o.name===name),at=name=>app.project(app.resolved.get(find(name).id).p),submit=()=> $('object-form').onsubmit({preventDefault(){}});
assert.equal($('tool').value,'select');assert.equal($('object-form').hidden,true);assert.equal(app.dimension,2);
// Direct selection and a genuine double-click coordinate edit.
click(at('B'));assert.equal(app.selected,find('B').id);$('board').ondblclick(ev(at('B')));assert.equal($('point-dialog').open,true);$('dialog-0').value='5';$('dialog-1').value='0';$('point-edit-form').onsubmit({preventDefault(){}});assert.equal(app.resolved.get(find('B').id).p[0],5);assert.equal($('point-dialog').open,false);$('undo').click();assert.equal(app.resolved.get(find('B').id).p[0],4);$('redo').click();assert.equal(app.resolved.get(find('B').id).p[0],5);
// Step-by-step canvas selections feed the actual reference selects.
app.setTool('segment');click(at('A'));assert.equal($('ref-0').value,find('A').id);assert.match($('canvas-instruction').textContent,/Bước 2/);click(at('C'));assert.equal($('ref-1').value,find('C').id);assert.match($('canvas-instruction').textContent,/Đã chọn đủ/);$('object-name').value='AC test';submit();assert.equal(find('AC test').kind,'segment');
// Quick input is atomic on failure, supports formulas, edits existing points.
app.quickPoints('M=(sqrt(9),2); N=(-2,1)');assert.equal(app.resolved.get(find('M').id).p[0],3);const before=app.objects.length;assert.throws(()=>app.quickPoints('Q=(1,2); R=(nope,3)'));assert.equal(app.objects.length,before);assert.equal(find('Q'),undefined);app.quickPoints('M=(6,2)');assert.equal(app.resolved.get(find('M').id).p[0],6);
app.setTool('circle');click(at('M'));$('object-name').value='circle M';$('radius').value='2';submit();assert.equal(app.resolved.get(find('circle M').id).c[0],6);
// Point click placement and snapping affect only mouse coordinates.
app.setTool('point');$('object-name').value='K';$('snap').checked=true;$('snap-step').value='0.5';click(app.project([1.24,-1.26,0]));assert.equal(app.resolved.get(find('K').id).p[0],1);assert.equal(app.resolved.get(find('K').id).p[1],-1.5);app.quickPoints('Exact=(1.24,-1.26)');assert.equal(app.resolved.get(find('Exact').id).p[0],1.24);
app.setTool('select');const start=at('K'),end=app.project([2.24,-2.26,0]);$('board').onpointerdown(ev(start));$('board').onpointermove(ev(end));$('board').onpointerup(ev(end));assert.equal(app.resolved.get(find('K').id).p[0],2);assert.equal(app.resolved.get(find('K').id).p[1],-2.5);
// Marks switch actually removes angle arcs/text, preserving measurement results.
assert.ok(app.markCount>0);$('marks').checked=true;commands.length=0;$('marks').onchange();const markOn=commands.length;assert.ok(commands.some(x=>x.key==='fillText'&&String(x.args[0]).includes('°')));$('marks').checked=false;commands.length=0;$('marks').onchange();assert.ok(commands.length<markOn);assert.ok(!commands.some(x=>x.key==='fillText'&&String(x.args[0]).includes('°')));assert.match($('marks-info').textContent,/Đang ẩn/);
const saved=JSON.parse(JSON.stringify(app.snapshot()));app.restore(saved);assert.equal(app.resolved.get(find('circle M').id).c[0],6);assert.equal($('marks').checked,false);
// Hidden edges respond to camera rotation, cube top follows its defining point.
const s=boot('#space'),sa=s.c.ConstructionApp;s.$('preset').value='cube';s.$('example').click();assert.equal(sa.objects.length,9);assert.ok([...sa.resolved.values()].every(q=>!q.error));assert.ok(s.commands.some(x=>x.key==='setLineDash'&&x.args[0]?.length));sa.quickPoints('E=(1,0,4)');const f=sa.objects.find(o=>o.name==='F');assert.equal(sa.resolved.get(f.id).p[0],4);assert.equal(sa.resolved.get(f.id).p[2],4);
sa.setView('xy');sa.setTool('point');s.$('placement-level').value='2';s.$('object-name').value='Z';s.click(sa.project([1.2,1.3,2]));const z=sa.objects.find(o=>o.name==='Z');assert.equal(sa.resolved.get(z.id).p[2],2);
sa.setTool('select');const sp=sa.project(sa.resolved.get(z.id).p);s.$('board').onpointerdown(s.ev(sp));s.$('board').onpointermove(s.ev(sa.project([2,2,2])));s.$('board').onpointerup(s.ev(sa.project([2,2,2])));assert.equal(sa.resolved.get(z.id).p[2],2);
s.$('preset').value='sphere';s.$('example').click();s.commands.length=0;s.$('hidden-lines').checked=true;s.$('hidden-lines').onchange();assert.ok(s.commands.some(x=>x.key==='setLineDash'&&x.args[0]?.length));assert.ok(s.commands.some(x=>x.key==='strokeStyle'&&x.args[0]!== '#8290a0'));s.commands.length=0;s.$('hidden-lines').checked=false;s.$('hidden-lines').onchange();assert.ok(!s.commands.some(x=>x.key==='setLineDash'&&x.args[0]?.length));
console.log('PASS: canvas selection, guided tools, double-click edit, quick input atomicity, point placement, drag, snapping, marks toggle, undo/redo, persistence, 3D plane placement, linked prism and hidden-line commands.');
// Old saved cube examples had only points/segments: preserve them but add a solid.
const coords=[[0,0,0],[3,0,0],[3,3,0],[0,3,0],[0,0,3],[3,0,3],[3,3,3],[0,3,3]],oldPoints=coords.map((p,i)=>({id:'old'+i,name:'ABCDEFGH'[i],kind:'point',coords:p,refs:[]}));const oldEdges=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]].map(([a,b],i)=>({id:'edge'+i,name:'edge'+i,kind:'segment',refs:['old'+a,'old'+b]}));sa.restore({app:'curvelab-construction',version:1,dimension:3,objects:[...oldPoints,...oldEdges]});assert.equal(sa.objects.filter(o=>o.kind==='hexahedron').length,1);assert.equal(sa.objects.filter(o=>o.kind==='point').length,8);assert.equal(sa.objects.filter(o=>o.kind==='segment'&&o.visible===false).length,12);assert.equal([...sa.resolved.values()].find(q=>q.type==='hexahedron').volume,27);
// Changing a center to a point added later still works with the new direct selection flow.
app.quickPoints('Later=(8,9)');const row=$('objects').children.find(row=>row.dataset.id===find('circle M').id);row.children[2].children[0].click();click(at('Later'));submit();assert.equal(app.resolved.get(find('circle M').id).c[0],8);
console.log('PASS: old cube migration and editing a circle center by clicking a later-created point.');
module.exports={boot};
