const assert=require('node:assert/strict'),fs=require('node:fs');
const {boot}=require('./construction-interaction.test.cjs');
function blank(hash=''){const t=boot(hash);t.$('preset').value='empty';t.$('example').click();return {...t,app:t.c.ConstructionApp};}
const t=blank(),{app,$,click}=t,go=p=>click(app.project(p)),count=k=>app.objects.filter(o=>o.kind===k).length;
// Three blank-space clicks create points and fill the current triangle, without mode changes.
app.setTool('triangle');$('object-name').value='Triangle';go([-2,-1,0]);const a=$('ref-0').value;assert.ok(a);assert.equal(count('point'),1);assert.equal($('tool').value,'triangle');go([2,-1,0]);const b=$('ref-1').value;go([0,2,0]);const c=$('ref-2').value;assert.equal(count('point'),3);assert.equal(count('triangle'),0);assert.equal($('finish-build').disabled,false);assert.equal($('object-name').value,'Triangle');
const view=JSON.stringify(app.view);$('undo').click();assert.equal(count('point'),2);assert.equal($('ref-0').value,a);assert.equal($('ref-1').value,b);assert.equal($('ref-2').value,'');assert.equal(JSON.stringify(app.view),view);$('redo').click();assert.equal(count('point'),3);assert.equal($('ref-2').value,c);
$('finish-build').click();assert.equal(count('triangle'),1);$('undo').click();assert.equal(count('triangle'),0);assert.equal($('ref-2').value,c);assert.equal($('object-name').value,'Triangle');$('redo').click();assert.equal(count('triangle'),1);
// Existing-point selection is itself an undoable step; redo does not create extra points.
app.setTool('line');const p=app.resolved.get(a).p;go(p);assert.equal($('ref-0').value,a);$('undo').click();assert.equal($('tool').value,'line');assert.equal($('ref-0').value,'');assert.equal(count('point'),3);$('redo').click();assert.equal($('ref-0').value,a);
// A new action after stepping back discards the obsolete redo branch.
$('undo').click();go([4,2,0]);assert.equal(count('point'),4);assert.equal($('redo').disabled,true);go([5,0,0]);$('finish-build').click();assert.equal(count('line'),1);
// Auto-build only finishes a complete selection. Undo of auto-build restores the draft.
app.setTool('segment');$('auto-build').checked=true;$('auto-build').onchange();go([-4,3,0]);assert.equal(count('segment'),0);go([-3,1,0]);assert.equal(count('segment'),1);assert.equal($('ref-0').value,'');$('undo').click();assert.equal(count('segment'),0);assert.ok($('ref-0').value&&$('ref-1').value);assert.equal($('auto-build').checked,true);$('redo').click();assert.equal(count('segment'),1);
// Dropdown selection and replacing a chosen slot are undoable too.
$('auto-build').checked=false;app.setTool('line');const sel=$('ref-0');sel.value=a;sel.onchange();assert.equal($('ref-0').value,a);$('undo').click();assert.equal($('ref-0').value,'');$('redo').click();assert.equal($('ref-0').value,a);$('ref-1').value=b;$('ref-1').onchange();$('ref-0').onfocus();const before=count('point');go([7,3,0]);assert.equal(count('point'),before+1);assert.notEqual($('ref-0').value,a);assert.equal($('ref-1').value,b);$('undo').click();assert.equal($('ref-0').value,a);assert.equal(count('point'),before);
// Real key handler: Ctrl+Z/Y for drafting; native undo remains in text fields.
let prevented=false;const key=(value,target={matches:()=>false},shiftKey=false)=>({ctrlKey:true,metaKey:false,altKey:false,shiftKey,key:value,target,preventDefault(){prevented=true;}});const refs=$('ref-1').value;t.events.keydown(key('z'));assert.equal(prevented,true);assert.equal($('ref-1').value,'');t.events.keydown(key('y'));assert.equal($('ref-1').value,refs);prevented=false;t.events.keydown(key('z',{matches:()=>true}));assert.equal(prevented,false);assert.equal($('ref-1').value,refs);
// Same workflow in 3D, respecting the working plane height for each new vertex.
const s=blank('#space'),sa=s.app;sa.setTool('tetrahedron');sa.setView('xy');s.$('auto-build').checked=true;s.$('auto-build').onchange();for(const q of [[0,0,0],[4,0,0],[0,3,0]])s.click(sa.project(q));assert.equal(sa.objects.filter(o=>o.kind==='tetrahedron').length,0);s.$('placement-level').value='4';s.click(sa.project([1,1,4]));assert.equal(sa.objects.filter(o=>o.kind==='tetrahedron').length,1);assert.equal([...sa.resolved.values()].find(q=>q.type==='tetrahedron').volume,8);s.$('undo').click();assert.equal(s.$('tool').value,'tetrahedron');assert.equal(s.$('placement-level').value,'4');s.$('redo').click();assert.equal(sa.objects.filter(o=>o.kind==='tetrahedron').length,1);
// Invalid auto construction reports the error and retains the draft for correction.
const d=blank();d.app.setTool('triangle');d.$('auto-build').checked=true;for(const q of [[-2,0,0],[0,0,0],[2,0,0]])d.click(d.app.project(q));assert.equal(d.app.objects.length,3);assert.match(d.$('error').textContent,/thẳng hàng/);assert.ok(d.$('ref-2').value);d.$('undo').click();assert.equal(d.app.objects.length,2);d.click(d.app.project([0,2,0]));assert.equal(d.app.objects.filter(o=>o.kind==='triangle').length,1);
// Presentation contract on all three entry pages, without changing their math engines.
for(const file of ['index.html','studio.html','construction.html']){const html=fs.readFileSync(__dirname+'/../../CurveLab/'+file,'utf8');assert.equal((html.match(/href="workspace.css"/g)||[]).length,1);assert.match(html,/<aside tabindex="0"/);assert.match(html,/<section class="workspace" tabindex="0"/);}
const html=fs.readFileSync(__dirname+'/../../CurveLab/construction.html','utf8');assert.ok(html.indexOf('id="objects"')>html.indexOf('id="board"'));assert.ok(!html.slice(html.indexOf('<aside'),html.indexOf('</aside>')).includes('id="objects"'));assert.equal((html.match(/id="objects"/g)||[]).length,1);
console.log('PASS: in-tool point creation, manual/automatic completion, draft undo/redo, view preservation, new redo branches, dropdown edits, keyboard shortcuts, invalid draft correction, 3D tetrahedron workflow and shared layout wiring.');
const q=blank();q.app.setTool('segment');q.click(q.app.project([-2,-2,0]));const first=q.$('ref-0').value;q.app.quickPoints('Extra=(3,2)');assert.equal(q.$('ref-0').value,first);assert.equal(q.$('ref-1').value,'');assert.ok(q.$('ref-1').options.some(o=>o.value===q.app.objects.find(p=>p.name==='Extra').id));
console.log('PASS: quick point entry preserves an unfinished construction.');
// Restart intentionally empties the drawing; the forward arrow never acts as reset.
for(const hash of ['', '#space']){const r=boot(hash),before=JSON.stringify(r.c.ConstructionApp.objects);r.$('restart').click();assert.equal(r.c.ConstructionApp.objects.length,0);r.$('undo').click();assert.equal(JSON.stringify(r.c.ConstructionApp.objects),before);r.$('redo').click();assert.equal(r.c.ConstructionApp.objects.length,0);r.$('undo').click();r.c.ConstructionApp.quickPoints(hash?'New=(7,8,9)':'New=(7,8)');const after=JSON.stringify(r.c.ConstructionApp.objects);r.$('undo').click();r.$('redo').click();assert.equal(JSON.stringify(r.c.ConstructionApp.objects),after);}
assert.ok(html.indexOf('id="tool"')<html.indexOf('id="quick-form"'));
const controls=html.slice(html.indexOf('class="build-history"'),html.indexOf('class="check auto-build-label"'));
for(const key of ['undo','redo','finish-build'])assert.ok(controls.includes('id="'+key+'"'));
assert.ok(!html.includes('id="step-back"'));assert.ok(!html.includes('>Hoàn tác</button>'));
console.log('PASS: restart/restore in 2D and 3D, redo preserves objects, arrow placement and tool-first order.');
