const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),T=require('../../CurveLab/tikz-export.js');
const out=path.resolve(__dirname,'../artifacts/tikz');fs.mkdirSync(out,{recursive:true});
assert.deepEqual(T.color('hsl(0 100% 50%)').rgb,[255,0,0]);assert.equal(T.color('#ffffff80').a,128/255);assert.match(T.escape('A_1%{x}\\input{secret}'),/\\textbackslash/);
assert.deepEqual(T.clipLine([-1,5],[11,5],[0,0,10,10]),[[0,5],[10,5]]);assert.equal(T.clipLine([-2,-2],[-1,-1],[0,0,10,10]),null);
const recorder=new T.Recorder(800,500);recorder.fillStyle='white';recorder.fillRect(0,0,800,500);recorder.strokeStyle='#1463d6';recorder.lineWidth=2;recorder.beginPath();recorder.moveTo(-1e9,200);recorder.lineTo(1e9,200);recorder.stroke();recorder.save();recorder.beginPath();recorder.rect(100,100,500,250);recorder.clip();recorder.fillStyle='rgba(255,169,65,.45)';recorder.beginPath();recorder.moveTo(80,80);recorder.lineTo(650,140);recorder.lineTo(400,400);recorder.closePath();recorder.fill();recorder.restore();recorder.setLineDash([5,4]);recorder.beginPath();recorder.arc(350,260,90,0,2*Math.PI);recorder.stroke();recorder.font='bold 18px Georgia';recorder.fillStyle='#000';recorder.fillText('Điểm A₁: 90° & 50% _ {x}',200,60);const basic=recorder.document({title:'Primitive test',formula:{tex:'\\begin{gathered}x(t)=\\cos t\\\\y(t)=\\sin t\\end{gathered}',corner:'right'}});assert.ok(!basic.includes('1000000000'));assert.match(basic,/documentclass\[varwidth=50cm,border=2pt\]\{standalone\}/);assert.match(basic,/ellipse/);assert.match(basic,/dash pattern/);assert.ok(!basic.includes('includegraphics'));fs.writeFileSync(path.join(out,'primitives.tex'),basic);
// Exercise exports from the actual construction renderer and check that export preserves the model.
const {boot}=require('./construction-interaction.test.cjs');
for(const [name,hash,preset] of [['triangle','','triangle'],['circle','','circle'],['tetrahedron','#space','tetrahedron'],['cube','#space','cube'],['sphere','#space','sphere']]){const t=boot(hash);t.$('preset').value=preset;t.$('example').click();const a=t.c.ConstructionApp,before=JSON.stringify(a.snapshot()),source=a.exportLatex();assert.equal(JSON.stringify(a.snapshot()),before);assert.match(source,/\\coordinate \(P1\)/);assert.match(source,/\\end\{document\}/);fs.writeFileSync(path.join(out,name+'.tex'),source);if(hash){assert.match(source,/dash pattern/);t.$('hidden-lines').checked=false;t.$('hidden-lines').onchange();assert.ok(!a.exportLatex().includes('dash pattern'));}t.$('labels').checked=false;t.$('marks').checked=false;t.$('axes').checked=false;t.$('grid').checked=false;t.$('labels').onchange();assert.ok(!a.exportLatex().includes('\\node['));}
for(const [f,load,exportId] of [['index.html','load','latex-export'],['construction.html','load','latex-export'],['studio.html','lab-load','lab-latex-export']]){const html=fs.readFileSync(path.join(__dirname,'../../CurveLab',f),'utf8');assert.ok(html.indexOf('id="'+exportId+'"')>html.indexOf('id="'+load+'"'));assert.equal((html.match(/src="tikz-export.js"/g)||[]).length,1);}
for(const [name,limit] of [['triangle',12000],['circle',10000],['sphere',25000]]){const source=fs.readFileSync(path.join(out,name+'.tex'),'utf8');assert.ok(Buffer.byteLength(source)<limit);assert.ok(source.indexOf('\\begin{center}')<source.indexOf('\\begin{tikzpicture}'));assert.ok(source.includes('\\resizebox{\\FigureWidth}{!}'));assert.ok(source.includes('declare function={figwidth='));assert.ok(source.includes('\\newcommand{\\FigureWidth}{16cm}'));}
console.log('PASS: compact TikZ size, central sizing control, centered picture, primitives, clipping, colors, safe labels, construction modes, hidden-line/label switches and unchanged model; fixtures in '+out);
