'use strict';
const $=id=>document.getElementById(id),canvas=$('canvas');
let ctx=canvas.getContext('2d');
const presets={
param:[['Đường tự cắt · bài của bạn','t^2-5','t^3-5*t','-3','3'],['Đường tự cắt · ví dụ ban đầu','t^2-4','t^3-4*t','-3.2','3.2'],['Đường tròn','cos(t)','sin(t)','0','2*pi'],['Elip','3*cos(t)','2*sin(t)','0','2*pi'],['Lissajous','sin(3*t)','sin(2*t)','0','2*pi'],['Cycloid','t-sin(t)','1-cos(t)','0','4*pi'],['Astroid','3*cos(t)^3','3*sin(t)^3','0','2*pi'],['Đường xoắn ốc','t*cos(t)','t*sin(t)','0','6*pi'],['Parabol bán lập phương','t^2','t^3','-2','2']],
cart:[['Parabol','','x^2','-3','3'],['Sóng sin','','sin(x)','-2*pi','2*pi'],['Đa thức bậc ba','','x^3-3*x','-2.5','2.5'],['Hàm mũ','','exp(x)','-3','3'],['Logarit','','ln(x)','0.1','5'],['Hàm hữu tỉ','','1/(1+x^2)','-5','5'],['Giá trị tuyệt đối','','abs(x)','-3','3']],
polar:[['Hoa hồng 5 cánh','','2*cos(5*theta)','0','2*pi'],['Cardioid','','1+cos(theta)','0','2*pi'],['Xoắn ốc Archimedes','','theta/3','0','6*pi'],['Đường tròn lệch tâm','','2*cos(theta)','0','2*pi'],['Hoa hồng 4 cánh','','2*sin(2*theta)','0','2*pi']]
};
let analysis=null,selectedT=null,pointHits=[],plotted=null,curve=null,view=null,W=0,H=0,playing=false,last=0,raf=0,debounce,drag=null;
const margins={l:72,r:22,t:24,b:48};
const fmt=n=>CurveFormat.format(n,$('fractions').checked);
const tickFmt=n=>CurveFormat.format(n,false);
function legacyConfig(){return {version:1,axes:$('axes').checked,coordinates:$('coordinates').checked,fractions:$('fractions').checked,showpoints:$('showpoints').checked,pointlabels:$('pointlabels').checked,projections:$('projections').checked,custompoints:$('custompoints').value,mode:$('mode').value,x:$('ex').value,y:$('ey').value,a:$('a').value,b:$('b').value,samples:Number($('samples').value),equal:$('equal').checked,grid:$('grid').checked,tangent:$('tangent').checked,auto:$('auto').checked,position:Number($('position').value)};}
function store(){try{localStorage.setItem('curvelab-v1',JSON.stringify(config()));}catch{}}
function legacySetMode(){const mode=$('mode').value,p=mode==='param',v=mode==='cart'?'x':mode==='polar'?'θ':'t';$('xfield').hidden=!p;$('ylabel').textContent=p?'y(t)':mode==='cart'?'f(x)':'r(θ)';$('alabel').textContent=v+' từ';$('blabel').textContent=v+' đến';$('paramname').textContent=v;$('charttitle').textContent=p?'Đường cong tham số':mode==='cart'?'Đồ thị hàm số':'Đường cong tọa độ cực';$('preset').replaceChildren();$('preset').add(new Option('Bài tùy chỉnh','custom')); for(let [i,row] of presets[mode].entries()){$('preset').add(new Option(row[0],i));}}
function applyPreset(){if($('preset').value==='custom')return;const row=presets[$('mode').value][Number($('preset').value)];$('ex').value=row[1];$('ey').value=row[2];$('a').value=row[3];$('b').value=row[4];$('position').value=5000;build();}
function legacyRestore(c){if(!c||c.version!==1||!Object.hasOwn(presets,c.mode))throw Error('Tệp không phải bài CurveLab phiên bản 1.');for(const k of ['x','y','a','b'])if(typeof c[k]!=='string'||c[k].length>300)throw Error('Tệp chứa biểu thức không hợp lệ.');CurveMath.makeCurve(c);$('mode').value=c.mode;setMode();for(const [key,id] of [['x','ex'],['y','ey'],['a','a'],['b','b']])$(id).value=c[key];$('samples').value=[1200,4000,12000].includes(c.samples)?c.samples:4000;for(const id of ['axes','equal','grid','tangent','auto','showpoints','pointlabels','projections','coordinates','fractions'])$(id).checked=c[id]!==false;$('position').value=Number.isFinite(c.position)?Math.min(10000,Math.max(0,c.position)):5000;$('preset').value='custom';$('custompoints').value=typeof c.custompoints==='string'?c.custompoints.slice(0,2000):'';build();}
function legacyBuild(){clearTimeout(debounce);stop();selectedT=null;try{curve=CurveMath.makeCurve(config());plotted=config();analysis=CurveAnalysis.analyze(curve,plotted.mode);renderAnalysis();$('error').textContent='';$('leftend').textContent=fmt(curve.a);$('rightend').textContent=fmt(curve.b);$('status').textContent=curve.omitted?`${curve.omitted} điểm không xác định hoặc ngoài giới hạn tọa độ đã được bỏ qua.`:'Tiếp tuyến và tọa độ được tính gần đúng bằng phương pháp số.';fit();store();}catch(e){curve=null;view=null;analysis=null;$('variation').replaceChildren();$('pointlist').replaceChildren();$('error').textContent=e.message;$('metrics').textContent='';$('status').textContent='';$('tvalue').textContent='—';$('leftend').textContent='';$('rightend').textContent='';draw();}}
function fitPlanar(){if(!curve)return;let [xmin,xmax,ymin,ymax]=curve.bounds;let dx=xmax-xmin||Math.max(1,Math.abs(xmin)*.2),dy=ymax-ymin||Math.max(1,Math.abs(ymin)*.2);dx*=1.15;dy*=1.15;const pw=Math.max(1,W-margins.l-margins.r),ph=Math.max(1,H-margins.t-margins.b);if($('equal').checked){const u=Math.max(dx/pw,dy/ph);dx=u*pw;dy=u*ph;}view={cx:(xmin+xmax)/2,cy:(ymin+ymax)/2,dx,dy};draw();}
function geometry(){const {l,r,t,b}=margins,pw=W-l-r,ph=H-t-b;return {l,t,pw,ph,sx:x=>l+(x-view.cx+view.dx/2)/view.dx*pw,sy:y=>t+(view.cy+view.dy/2-y)/view.dy*ph,ix:p=>view.cx-view.dx/2+(p-l)/pw*view.dx,iy:p=>view.cy+view.dy/2-(p-t)/ph*view.dy};}
function ticks(lo,hi,count){const raw=(hi-lo)/count,base=10**Math.floor(Math.log10(raw)),q=raw/base,step=(q<=1?1:q<=2?2:q<=5?5:10)*base,values=[];if(!Number.isFinite(step)||step<=0)return values;for(let i=Math.ceil(lo/step),j=0;j<30&&i*step<=hi;i++,j++)values.push(i*step);return values;}
function line(x1,y1,x2,y2,color,width=1,dash=[]){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.setLineDash([]);}
function drawPlanar(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#ffffff';if(ctx.objectsOnly!==true)ctx.fillRect(0,0,W,H);ctx.font='12px system-ui';ctx.fillStyle='#61777d';if(!curve||!view){ctx.textAlign='center';ctx.fillText('Nhập biểu thức hợp lệ để vẽ đường cong',W/2,H/2);return;}const {l,t,pw,ph,sx,sy}=geometry(),xmin=view.cx-view.dx/2,xmax=view.cx+view.dx/2,ymin=view.cy-view.dy/2,ymax=view.cy+view.dy/2;const tx=ticks(xmin,xmax,W<500?3:6),ty=ticks(ymin,ymax,6);
 ctx.save();ctx.beginPath();ctx.rect(l,t,pw,ph);ctx.clip();if(ctx.objectsOnly!==true&&$('grid').checked){tx.forEach(v=>line(sx(v),t,sx(v),t+ph,'#e9eff0'));ty.forEach(v=>line(l,sy(v),l+pw,sy(v),'#e9eff0'));}if(ctx.objectsOnly!==true&&$('axes').checked&&xmin<=0&&xmax>=0)line(sx(0),t,sx(0),t+ph,'#111');if(ctx.objectsOnly!==true&&$('axes').checked&&ymin<=0&&ymax>=0)line(l,sy(0),l+pw,sy(0),'#111');
 ctx.beginPath();ctx.strokeStyle='#1463d6';ctx.lineWidth=2.7;let prev=null;const threshold=Math.hypot(pw,ph)*.65;
 for(const p of curve.data){if(!curve.valid(p)){prev=null;continue;}const px=sx(p.x),py=sy(p.y);let join=!!prev;if(prev){const dist=Math.hypot(px-sx(prev.x),py-sy(prev.y));if(dist>threshold)join=false;else{const mid=curve.point((prev.t+p.t)/2);if(!curve.valid(mid)||Math.hypot(sx(mid.x)-(px+sx(prev.x))/2,sy(mid.y)-(py+sy(prev.y))/2)>Math.max(5,dist*.6))join=false;}}if(join)ctx.lineTo(px,py);else ctx.moveTo(px,py);prev=p;}ctx.stroke();
 const param=selectedT??(curve.a+(curve.b-curve.a)*Number($('position').value)/10000),p=curve.point(param),d=CurveMath.derivative(curve,param);$('tvalue').textContent=fmt(param);typeset($('tvalue'));typeset($('leftend'));typeset($('rightend'));
 if(curve.valid(p)){if($('tangent').checked&&d.ok){const vx=d.dx/view.dx*pw,vy=-d.dy/view.dy*ph,n=Math.hypot(vx,vy),len=Math.hypot(pw,ph)*2;line(sx(p.x)-vx/n*len,sy(p.y)-vy/n*len,sx(p.x)+vx/n*len,sy(p.y)+vy/n*len,'#c45b16',1.8,[7,5]);}ctx.beginPath();ctx.arc(sx(p.x),sy(p.y),5.5,0,Math.PI*2);ctx.fillStyle='#c62855';ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='white';ctx.stroke();}ctx.restore();
 drawSurveyPoints();if(curve.valid(p)&&sx(p.x)>=l&&sx(p.x)<=l+pw&&sy(p.y)>=t&&sy(p.y)<=t+ph){ctx.beginPath();ctx.arc(sx(p.x),sy(p.y),5.5,0,Math.PI*2);ctx.fillStyle='#c62855';ctx.fill();ctx.lineWidth=1.5;ctx.strokeStyle='white';ctx.stroke();}drawAxes();drawPointNames();
 const parts=curve.valid(p)?[`Điểm ≈ (${fmt(p.x)}; ${fmt(p.y)})`,d.ok?`Đạo hàm ≈ (${fmt(d.dx)}, ${fmt(d.dy)})`:'Tiếp tuyến: chưa xác định bằng đạo hàm số',d.ok?(Math.abs(d.dx)<1e-8?`Tiếp tuyến đứng: x ≈ ${fmt(p.x)}`:`Tiếp tuyến: y − (${fmt(p.y)}) ≈ ${fmt(d.dy/d.dx)} · [x − (${fmt(p.x)})]`):null]:['Điểm không xác định tại tham số này.'];$('metrics').replaceChildren(...parts.filter(Boolean).map(text=>{const el=document.createElement('span');el.textContent=text;typeset(el);return el;}));
}
function resize(){const rect=canvas.getBoundingClientRect(),oldW=W,oldH=H;W=rect.width;H=rect.height;const ratio=Math.min(window.devicePixelRatio||1,3);canvas.width=Math.round(W*ratio);canvas.height=Math.round(H*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);if(view&&$('equal').checked&&oldW&&oldH){view.dx*=(W-margins.l-margins.r)/(oldW-margins.l-margins.r);view.dy*=(H-margins.t-margins.b)/(oldH-margins.t-margins.b);}draw();}
function stop(){playing=false;cancelAnimationFrame(raf);$('play').textContent='▶ Chạy';$('play').setAttribute('aria-pressed','false');$('metrics').setAttribute('aria-live','polite');}
function frame(time){if(!playing)return;const dt=Math.min(time-last,100);last=time;const value=Number($('position').value)+dt/1.6;$('position').value=Math.min(10000,value);draw();if(value>=10000){stop();store();}else raf=requestAnimationFrame(frame);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
$('form').onsubmit=e=>{e.preventDefault();build();};$('mode').onchange=()=>{setMode();$('preset').value='0';applyPreset();};$('preset').onchange=applyPreset;
for(const id of ['ex','ey','a','b'])$(id).oninput=()=>{$('preset').value='custom';clearTimeout(debounce);if($('auto').checked)debounce=setTimeout(build,500);else $('status').textContent='Biểu thức đã thay đổi. Bấm Vẽ để cập nhật.';};
$('samples').onchange=build;$('equal').onchange=()=>{fit();store();};for(const id of ['axes','grid','tangent'])$(id).onchange=()=>{draw();store();};$('auto').onchange=()=>{if($('auto').checked)build();else{clearTimeout(debounce);store();}};
$('position').oninput=()=>{stop();selectedT=null;draw();};$('position').onchange=store;$('fit').onclick=fit;
$('play').onclick=()=>{if(playing){stop();draw();store();return;}if(!curve)return;selectedT=null;if(Number($('position').value)>=10000)$('position').value=0;playing=true;$('play').textContent='Ⅱ Dừng';$('play').setAttribute('aria-pressed','true');$('metrics').setAttribute('aria-live','off');last=performance.now();raf=requestAnimationFrame(frame);};
canvas.onwheel=e=>{if(!view)return;e.preventDefault();const rect=canvas.getBoundingClientRect(),px=e.clientX-rect.left,py=e.clientY-rect.top,g=geometry();if(px<g.l||px>g.l+g.pw||py<g.t||py>g.t+g.ph)return;const factor=Math.exp(Math.max(-.4,Math.min(.4,e.deltaY*.001))),dx=view.dx*factor,dy=view.dy*factor;if(dx<1e-9||dy<1e-9||dx>1e15||dy>1e15)return;const ax=g.ix(px),ay=g.iy(py);view.cx=ax+(view.cx-ax)*factor;view.cy=ay+(view.cy-ay)*factor;view.dx=dx;view.dy=dy;draw();};
canvas.onpointerdown=e=>{if(!view)return;drag={x:e.clientX,y:e.clientY,cx:view.cx,cy:view.cy};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag||!view)return;const {pw,ph}=geometry();view.cx=drag.cx-(e.clientX-drag.x)/pw*view.dx;view.cy=drag.cy+(e.clientY-drag.y)/ph*view.dy;draw();};canvas.onpointerup=e=>{if(drag&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<5){const rect=canvas.getBoundingClientRect();const hit=pointHits.find(p=>Math.hypot(p.x-e.clientX+rect.left,p.y-e.clientY+rect.top)<16);if(hit)selectPoint(hit.t);}drag=null;};canvas.onpointercancel=()=>{drag=null;};
$('png').onclick=()=>{if(!curve)return;$('status').textContent='Đang xuất ảnh…';const exportCanvas=document.createElement('canvas'),scale=2;exportCanvas.width=Math.round(W*scale);exportCanvas.height=Math.round((H+72)*scale);const c=exportCanvas.getContext('2d');c.scale(scale,scale);c.fillStyle='white';c.fillRect(0,0,W,H+72);c.fillStyle='#182e34';c.font='600 16px system-ui';c.fillText('CurveLab · '+$('charttitle').textContent,20,26);c.font='12px system-ui';const mode=plotted.mode,title=mode==='param'?`x(t) = ${plotted.x}; y(t) = ${plotted.y}`:mode==='cart'?`y = ${plotted.y}`:`r(θ) = ${plotted.y}`;c.fillText(title,20,49,W-40);c.drawImage(canvas,0,64,W,H);exportCanvas.toBlob(blob=>{if(blob){download(blob,'curvelab.png');$('status').textContent='Đã tạo ảnh PNG.';}else $('status').textContent='Không tạo được ảnh.';});};
$('save').onclick=()=>{try{CurveMath.makeCurve(config());download(new Blob([JSON.stringify(config(),null,2)],{type:'application/json'}),'curvelab-bai.json');}catch(e){$('error').textContent=e.message;}};$('load').onclick=()=>$('file').click();$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;try{if(f.size>20000)throw Error('Tệp bài quá lớn (tối đa 20 KB).');restore(JSON.parse(await f.text()));}catch(e){$('error').textContent='Không mở được bài: '+e.message;}$('file').value='';};
function selectPoint(t){stop();selectedT=t;$('position').value=(t-curve.a)/(curve.b-curve.a)*10000;draw();store();}
function surveyGroups(){if(!analysis)return [];const groups=analysis.groups.slice(0,80).map(g=>({...g,branches:[...g.branches]}));let errors=[];const parts=$('custompoints').value.split(';').map(s=>s.trim()).filter(Boolean);if(parts.length>30)errors.push('Chỉ nhận tối đa 30 mốc thêm.');for(const source of parts.slice(0,30)){try{const t=CurveMath.compile(source,'constant',curve.constants||{
})();if(!Number.isFinite(t)||t<curve.a||t>curve.b)throw Error('ngoài khoảng đang vẽ');const p=curve.point(t);if(!curve.valid(p))throw Error('điểm không xác định');const tolerance=Math.max(1,...curve.bounds.map(Math.abs))*1e-7;let g=groups.find(g=>Math.hypot(g.x-p.x,g.y-p.y,(g.z||0)-(p.z||0))<tolerance);if(!g){g={...p,label:`P${groups.length+1}`,branches:[]};groups.push(g);}if(!g.branches.some(b=>Math.abs(b.t-t)<1e-8))g.branches.push({t,...p,kinds:['Mốc thêm']});}catch(e){errors.push(`${source}: ${e.message}`);}}$('pointerror').textContent=errors.join(' · ');return groups;}
let activeGroups=[];
function cell(tag,text){const el=document.createElement(tag);el.textContent=text;typeset(el);return el;}
function markButton(t,label){const b=document.createElement('button');b.type='button';b.className='point-button';b.textContent=label;typeset(b);b.onclick=()=>selectPoint(t);return b;}
function renderPlanarAnalysis(){if(!analysis)return;activeGroups=surveyGroups();const mode=plotted.mode,param=mode==='cart'?'x':mode==='polar'?'θ':'t',keys=mode==='cart'?['y']:mode==='space'?['x','y','z']:['x','y'];$('variationnote').textContent=`Khảo sát số theo ${param} trên [${fmt(curve.a)}, ${fmt(curve.b)}]${mode==='polar'?' · x = r cos θ, y = r sin θ':''}. ↗ tăng; ↘ giảm; → gần như không đổi; ? chưa xác định. Giá trị hiển thị là gần đúng.`+(analysis.limited?' Nhiều mốc: bảng chỉ giữ 40 mốc đầu và cuối khoảng; hãy thu hẹp khoảng.':'');
const table=document.createElement('table');table.className='variation-table';const head=document.createElement('thead'),hr=document.createElement('tr');hr.append(cell('th',param));analysis.knots.forEach((t,i)=>{const th=document.createElement('th');th.append(markButton(t,fmt(t)));hr.append(th);if(i<analysis.knots.length-1)hr.append(cell('th',''));});head.append(hr);table.append(head);const body=document.createElement('tbody');
for(const key of keys){const dr=document.createElement('tr'),vr=document.createElement('tr');dr.append(cell('th',`${key}′(${param})`));vr.append(cell('th',`${key}(${param})`));analysis.knots.forEach((t,i)=>{const p=curve.point(t),d=CurveMath.derivative(curve,t),dv=d[key==='x'?'dx':key==='y'?'dy':'dz'];const smooth=d.ok||Math.hypot(d.dx,d.dy,d.dz||0)<1e-7;dr.append(cell('td',!curve.valid(p)||!Number.isFinite(dv)||!smooth?'—':Math.abs(dv)<1e-6?'0':dv>0?'+':'−'));vr.append(cell('td',curve.valid(p)?fmt(p[key]):'KXĐ'));if(i<analysis.intervals.length){const sign=analysis.intervals[i][key==='x'?'dx':key==='y'?'dy':'dz'];dr.append(cell('td',sign));const arrow=cell('td',sign==='+'?'↗':sign==='−'?'↘':sign==='0'?'→':'?');arrow.className='variation-arrow';vr.append(arrow);}});body.append(dr,vr);}table.append(body);$('variation').replaceChildren(table);
const list=document.createElement('div');list.className='point-cards';for(const g of activeGroups){const card=document.createElement('div');card.className='point-card';card.append(cell('strong',`${g.label} ≈ (${fmt(g.x)}; ${fmt(g.y)}${mode==='space'?'; '+fmt(g.z):''})`));for(const branch of g.branches){const row=document.createElement('div');row.className='point-branch';row.append(markButton(branch.t,`${param} ≈ ${fmt(branch.t)}`),cell('span',branch.kinds.join(' · ')));card.append(row);}list.append(card);}$('pointlist').replaceChildren(list);if(analysis.groups.length>80)$('pointlist').prepend(cell('p','Hiển thị tối đa 80 điểm tự động. Thu hẹp khoảng để xem chi tiết.'));
}
let annotationBoxes=[];
function mathSize(text){ctx.font='16px "Cambria Math", "Times New Roman", serif';const pieces=text.split('/');return {w:Math.max(...pieces.map(p=>ctx.measureText(p).width))+8,h:pieces.length===2?38:23};}
function mathPaint(text,x,y){const box=mathSize(text),parts=text.split('/');ctx.save();ctx.fillStyle='#111';ctx.textAlign='center';ctx.textBaseline='middle';ctx.strokeStyle='#111';ctx.lineWidth=1.2;if(parts.length===2){ctx.fillText(parts[0],x+box.w/2,y+9);line(x+3,y+19,x+box.w-3,y+19,'#111',1.2);ctx.fillText(parts[1],x+box.w/2,y+29);}else ctx.fillText(text,x+box.w/2,y+box.h/2);ctx.restore();}
function intersects(b){return annotationBoxes.some(a=>b.x<a.x+a.w+5&&b.x+b.w+5>a.x&&b.y<a.y+a.h+4&&b.y+b.h+4>a.y);}
function drawAxes(){annotationBoxes=[];if(ctx.objectsOnly===true||!$('axes').checked)return;const {l,t,pw,ph,sx,sy}=geometry(),ax=sx(0),ay=sy(0),hasX=ay>=t&&ay<=t+ph,hasY=ax>=l&&ax<=l+pw;
if(hasX)line(l,ay,l+pw,ay,'#111',1.7);if(hasY)line(ax,t,ax,t+ph,'#111',1.7);
const entries=[];const coords=$('coordinates').checked&&$('showpoints').checked;
if(coords)for(const g of activeGroups)for(const axis of ['x','y']){const value=g[axis];if(!entries.some(e=>e.axis===axis&&Math.abs(e.value-value)<1e-7))entries.push({axis,value,special:true});}
for(const value of ticks(view.cx-view.dx/2,view.cx+view.dx/2,W<500?3:6))if(!entries.some(e=>e.axis==='x'&&Math.abs(e.value-value)<1e-7))entries.push({axis:'x',value,special:false});
for(const value of ticks(view.cy-view.dy/2,view.cy+view.dy/2,6))if(!entries.some(e=>e.axis==='y'&&Math.abs(e.value-value)<1e-7))entries.push({axis:'y',value,special:false});
for(const e of entries){const horizontal=e.axis==='x',pos=horizontal?sx(e.value):sy(e.value),base=horizontal?(hasX?ay:t+ph):(hasY?ax:l);if(pos<(horizontal?l:t)+3||pos>(horizontal?l+pw:t+ph)-3)continue;
if(horizontal)line(pos,base-3,pos,base+3,'#111',1.2);else line(base-3,pos,base+3,pos,'#111',1.2);
let text=e.special?fmt(e.value):tickFmt(e.value);if(text.includes('.')&&!text.includes('/'))text=Number(e.value.toPrecision(4)).toString();const s=mathSize(text);const candidates=horizontal?[[pos-s.w/2,base+8],[pos-s.w/2,base-s.h-8],[pos-s.w/2,base+s.h+15],[pos-s.w/2,base-2*s.h-15],[pos-s.w/2,base+2*s.h+22]]:[[base-s.w-9,pos-s.h/2],[base+9,pos-s.h/2],[base-2*s.w-16,pos-s.h/2],[base+s.w+16,pos-s.h/2],[base-3*s.w-23,pos-s.h/2]];
for(const [x,y] of candidates){const b={x,y,...s};if(x<3||x+s.w>W-3||y<3||y+s.h>H-3||intersects(b))continue;if(e.special&&((horizontal&&Math.abs(y-base)>s.h+10)||(!horizontal&&Math.min(Math.abs(x-base),Math.abs(x+s.w-base))>s.w+10))){if(horizontal)line(pos,base,pos,y>base?y:y+s.h,'#777',.7,[2,3]);else line(base,pos,x>base?x:x+s.w,pos,'#777',.7,[2,3]);}mathPaint(text,x,y);annotationBoxes.push({...b,axis:e.axis,value:e.value,special:e.special});break;}}
ctx.font='italic bold 18px "Times New Roman",serif';ctx.fillStyle='#111';ctx.textAlign='right';ctx.fillText('x',l+pw-3,(hasX?ay:t+ph)-12);ctx.textAlign='left';ctx.fillText('y',(hasY?ax:l)+10,t+15);
}
function drawSurveyPoints(){pointHits=[];if(!analysis||!$('showpoints').checked)return;const {l,t,pw,ph,sx,sy}=geometry();const visible=activeGroups.filter(g=>sx(g.x)>=l&&sx(g.x)<=l+pw&&sy(g.y)>=t&&sy(g.y)<=t+ph);
ctx.save();ctx.beginPath();ctx.rect(l,t,pw,ph);ctx.clip();if(ctx.objectsOnly!==true&&$('axes').checked&&$('projections').checked)for(const g of visible){const x=sx(g.x),y=sy(g.y);line(x,y,x,sy(0),'#777',1,[4,5]);line(x,y,sx(0),y,'#777',1,[4,5]);}ctx.restore();
for(const g of visible){const x=sx(g.x),y=sy(g.y);ctx.beginPath();ctx.arc(x,y,4.2,0,Math.PI*2);ctx.fillStyle='#087c83';ctx.fill();pointHits.push({x,y,t:g.branches[0].t});}
}
function drawPointNames(){if(!analysis||!$('showpoints').checked||!$('pointlabels').checked)return;const {l,t,pw,ph,sx,sy}=geometry();ctx.font='bold 13px "Times New Roman",serif';ctx.fillStyle='#111';ctx.textAlign='left';ctx.textBaseline='middle';
for(const g of activeGroups){const x=sx(g.x),y=sy(g.y);if(x<l||x>l+pw||y<t||y>t+ph)continue;const w=ctx.measureText(g.label).width+2,h=18;let found=false;for(const gap of [9,22,38,55]){for(const [bx,by] of [[x+gap,y-h-4],[x-w-gap,y-h-4],[x+gap,y+5],[x-w-gap,y+5]]){const b={x:bx,y:by,w,h};if(bx<l||bx+w>l+pw||by<t||by+h>t+ph||intersects(b))continue;ctx.fillText(g.label,bx,by+h/2);annotationBoxes.push(b);found=true;break;}if(found)break;}}
}
function typeset(el){const walk=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);const nodes=[];while(walk.nextNode())if(!walk.currentNode.parentElement.closest('.math-frac'))nodes.push(walk.currentNode);for(const node of nodes){const text=node.textContent,re=/-?(?:\d*√\d+|\d*π|\d+)\/\d+/g;let m,start=0;const fragment=document.createDocumentFragment();while((m=re.exec(text))){fragment.append(document.createTextNode(text.slice(start,m.index)));const f=document.createElement('span');f.className='math-frac';f.setAttribute('aria-label',m[0]);const [num,den]=m[0].split('/');const top=document.createElement('span'),bottom=document.createElement('span');top.textContent=num;bottom.textContent=den;f.append(top,bottom);fragment.append(f);start=m.index+m[0].length;}if(start){fragment.append(document.createTextNode(text.slice(start)));node.replaceWith(fragment);}}}

for(const id of ['showpoints','pointlabels','projections','coordinates'])$(id).onchange=()=>{draw();store();};
$('fractions').onchange=()=>{if(analysis)renderAnalysis();if(curve){$('leftend').textContent=fmt(curve.a);$('rightend').textContent=fmt(curve.b);}draw();store();};
$('addpoints').onclick=()=>{if(!analysis)return;renderAnalysis();draw();store();};
$('custompoints').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('addpoints').click();}});

// Differential geometry extension. Existing 2D chart and saved files remain supported.
presets.space=[['Nút ba lá (trefoil)','(2+cos(3t))*cos(2t)','(2+cos(3t))*sin(2t)','0','2*pi','sin(3t)'],['Đường xoắn đinh ốc','a*cos(t)','a*sin(t)','0','4*pi','r*t'],['Đường cubic · 1.1.1b','t','t^2','-2','2','t^3'],['Bài 1.1.10 · độ dài cung','a*t','a*t^3/3','1','3','a/(2t)']];
presets.implicit=[['Bài 1.1.6 · đường hình trái tim','','x^2+(y-cbrt(x^2))^2=1','-1.4','1.4'],['Đường tròn','','x^2+y^2=1','-1.5','1.5'],['Lemniscate','','(x^2+y^2)^2=2(x^2-y^2)','-2','2']];
presets.param.push(['Bài 1.1.7 · đường con cá','cos(t)-sin(t)^2/sqrt(2)','sin(2t)/2','-pi','pi'],['Bài 1.1.6 · tham số hóa','cos(t)','sin(t)+cbrt(cos(t)^2)','0','2*pi'],['Bài 1.1.11 · cycloid theo đề','r*(t+sin(t))','r*(1-cos(t))','0','2*pi'],['Bài 1.1.5 · đường con bướm','sin(t)*(exp(cos(t))-2*cos(4t)-sin(t/12)^5)','cos(t)*(exp(cos(t))-2*cos(4t)-sin(t/12)^5)','-pi','pi']);
let geoLength=null,lastInput=$('ex'),camera={yaw:.65,pitch:.5,zoom:1},spaceBounds=null;
function config(){return {...legacyConfig(),z:$('ez').value,constants:$('constants').value,ymin:$('ymin').value,ymax:$('ymax').value,formulaCorner:$('formula-corner').value};}
function setMode(){legacySetMode();const m=$('mode').value,implicit=m==='implicit',space=m==='space';$('xfield').hidden=!(m==='param'||space);$('zfield').hidden=!space;$('implicitbounds').hidden=!implicit;$('camera-controls').hidden=!space;$('ylabel').textContent=implicit?'Phương trình F(x,y) = 0':space?'y(t)':$('ylabel').textContent;$('alabel').textContent=implicit?'x từ':space?'t từ':$('alabel').textContent;$('blabel').textContent=implicit?'x đến':space?'t đến':$('blabel').textContent;$('paramname').textContent=space?'t':$('paramname').textContent;$('charttitle').textContent=implicit?'Đường cong ẩn':space?'Đường cong trong không gian':$('charttitle').textContent;document.querySelector('.playback').hidden=implicit;$('differential').hidden=implicit;document.querySelector('.toolbar .hint').textContent=space?'Kéo để xoay · Cuộn để phóng to':'Cuộn để phóng to · Kéo hình để di chuyển';lastInput=$('ey');previewFormulas();}
function applyPreset(){if($('preset').value==='custom')return;const row=presets[$('mode').value][Number($('preset').value)];$('ex').value=row[1];$('ey').value=row[2];$('a').value=row[3];$('b').value=row[4];$('ez').value=row[5]||'0';$('position').value=5000;if($('mode').value==='implicit'){$('ymin').value='-1.5';$('ymax').value='2.5';}build();}
function restore(c){$('formula-corner').value=['left','right','hidden'].includes(c?.formulaCorner)?c.formulaCorner:'right';if(!c||c.version!==1||!Object.hasOwn(presets,c.mode))throw Error('Tệp bài không hợp lệ.');for(const k of ['x','y','a','b'])if(typeof c[k]!=='string'||c[k].length>600)throw Error('Biểu thức trong tệp không hợp lệ.');const check={...c,z:c.z||'0',constants:typeof c.constants==='string'?c.constants:'a=1; r=1',ymin:c.ymin||'-2',ymax:c.ymax||'2'};if(c.mode==='implicit')CurveAdvanced.implicit(check);else CurveMath.makeCurve(check);$('mode').value=c.mode;for(const [key,id] of [['x','ex'],['y','ey'],['a','a'],['b','b'],['z','ez'],['constants','constants'],['ymin','ymin'],['ymax','ymax']])$(id).value=check[key];setMode();$('samples').value=[1200,4000,12000].includes(c.samples)?c.samples:4000;for(const id of ['axes','equal','grid','tangent','auto','showpoints','pointlabels','projections','coordinates','fractions'])$(id).checked=c[id]!==false;$('position').value=Number.isFinite(c.position)?Math.max(0,Math.min(10000,c.position)):5000;$('custompoints').value=typeof c.custompoints==='string'?c.custompoints.slice(0,2000):'';$('preset').value='custom';build();}
function build(){clearTimeout(debounce);stop();selectedT=null;previewFormulas();try{plotted=config();curve=plotted.mode==='implicit'?CurveAdvanced.implicit(plotted):CurveMath.makeCurve(plotted);analysis=curve.implicit?null:CurveAnalysis.analyze(curve,plotted.mode);geoLength=curve.implicit?null:CurveGeometry.length(curve);renderAnalysis();$('error').textContent='';if(!curve.implicit){$('leftend').textContent=fmt(curve.a);$('rightend').textContent=fmt(curve.b);$('status').textContent=curve.omitted?`${curve.omitted} điểm bị bỏ qua do ngoài miền xác định.`:'Đạo hàm theo quy tắc giải tích; giá trị và bảng biến thiên vẫn là tính số.';}fit();renderPlotFormula();store();}catch(e){$('plot-formula').replaceChildren();curve=null;analysis=null;view=null;geoLength=null;$('error').textContent=e.message;for(const id of ['variation','pointlist','geometry-summary','geometry-point','derivative-formulas','metrics'])$(id).replaceChildren();$('solution-guide').textContent='Sửa ô có thông báo lỗi; công thức sẽ xuất hiện trong góc hình sau khi vẽ được.';draw();}}
function fit(){if(curve?.mode==='space'){const valid=curve.data.filter(curve.valid),ranges=['x','y','z'].map(k=>[Math.min(...valid.map(p=>p[k])),Math.max(...valid.map(p=>p[k]))]);spaceBounds={center:ranges.map(r=>(r[0]+r[1])/2),radius:Math.max(1e-6,...ranges.map(r=>(r[1]-r[0])/2))};camera.zoom=1;draw();}else if(curve?.implicit){view={cx:(curve.bounds[0]+curve.bounds[1])/2,cy:(curve.bounds[2]+curve.bounds[3])/2,dx:curve.bounds[1]-curve.bounds[0],dy:curve.bounds[3]-curve.bounds[2]};if($('equal').checked){const u=Math.max(view.dx/(W-margins.l-margins.r),view.dy/(H-margins.t-margins.b));view.dx=u*(W-margins.l-margins.r);view.dy=u*(H-margins.t-margins.b);}draw();}else fitPlanar();}
function draw(){if(curve?.implicit)drawImplicit();else if(curve?.mode==='space')drawSpace();else drawPlanar();if(curve&&!curve.implicit)pointGeometry();}
function renderAnalysis(){if(curve.implicit){activeGroups=[];$('variationnote').textContent='Phương trình ẩn có thể có nhiều nhánh y với cùng một x.';$('variation').textContent='Không lập một bảng biến thiên chung cho các nhánh. Hãy tham số hóa đường cong hoặc tách từng nhánh thành y = f(x).';$('pointlist').textContent=curve.segments.length?'Đang vẽ đường mức F(x,y)=0. Điểm đặc biệt và bảng biến thiên dùng chế độ tham số.':'Không thấy đường mức trong cửa sổ này. Thử thay khoảng x, y hoặc tăng độ chi tiết.';}else{renderPlanarAnalysis();const lengthText=geoLength.converged?`Độ dài cung L ≈ ${Number(geoLength.value.toPrecision(9))}. Chênh lệch giữa hai lưới ≈ ${Number(geoLength.error.toPrecision(2))} (không phải chặn sai số được chứng minh).`:`Độ dài chưa xác nhận: ${geoLength.reason||'tích phân không ổn định'}`;$('geometry-summary').textContent=lengthText;const warnings=curve.data.filter((p,i)=>i%4===0).filter(p=>{const d=CurveMath.derivative(curve,p.t);return !d.ok;});$('geometry-summary').append(cell('p',warnings.length?`Phát hiện ${warnings.length} mốc lấy mẫu có tốc độ gần 0 hoặc đạo hàm không xác định. Kiểm tra chính quy tại các mốc này.`:'Chưa phát hiện tốc độ bằng 0 trên lưới lấy mẫu; điều này không chứng minh chính quy trên toàn khoảng.'));$('derivative-formulas').replaceChildren();curve.derivatives[0].slice(0,curve.mode==='space'?3:2).forEach((f,i)=>{const row=cell('div','');row.className='formula-row';row.append(CurveLatex.node(`${['x','y','z'][i]}' = `+CurveLatex.ast(f.ast)));$('derivative-formulas').append(row);});}renderGuide();}
function pointGeometry(){const t=selectedT??curve.a+(curve.b-curve.a)*Number($('position').value)/10000,g=CurveGeometry.at(curve,t),n=v=>Number.isFinite(v)?Number(v.toPrecision(7)).toString():'không xác định';$('geometry-point').textContent=`Tại ${curve.mode==='cart'?'x':curve.mode==='polar'?'θ':'t'} ≈ ${n(t)}: tốc độ v ≈ ${n(g.speed)}; độ cong κ ≈ ${n(g.curvature)}${curve.mode==='space'?`; độ xoắn τ ≈ ${n(g.torsion)}`:''}.`+(g.regular?'':' Không xác định được tiếp tuyến/Frenet tại mốc này.');}
function drawImplicit(){ctx.clearRect(0,0,W,H);ctx.fillStyle='white';if(ctx.objectsOnly!==true)ctx.fillRect(0,0,W,H);if(!view)return;const {l,t,pw,ph,sx,sy}=geometry();ctx.save();ctx.beginPath();ctx.rect(l,t,pw,ph);ctx.clip();ctx.beginPath();ctx.strokeStyle='#1463d6';ctx.lineWidth=2;for(const [a,b] of curve.segments){ctx.moveTo(sx(a.x),sy(a.y));ctx.lineTo(sx(b.x),sy(b.y));}ctx.stroke();ctx.restore();drawAxes();pointHits=[];}
function project(p){const q=[p.x-spaceBounds.center[0],p.y-spaceBounds.center[1],p.z-spaceBounds.center[2]],a=camera.yaw,b=camera.pitch,x=Math.cos(a)*q[0]-Math.sin(a)*q[1],y=Math.sin(a)*q[0]+Math.cos(a)*q[1],v=Math.cos(b)*y-Math.sin(b)*q[2],depth=Math.sin(b)*y+Math.cos(b)*q[2],scale=Math.min(W-100,H-100)/(spaceBounds.radius*2.6)*camera.zoom;return {x:W/2+x*scale,y:H/2-v*scale,depth};}
function drawSpace(){ctx.clearRect(0,0,W,H);ctx.fillStyle='white';if(ctx.objectsOnly!==true)ctx.fillRect(0,0,W,H);if(!spaceBounds)return;pointHits=[];const r=spaceBounds.radius,center=spaceBounds.center;ctx.font='bold 14px serif';if(ctx.objectsOnly!==true&&$('axes').checked)for(let k=0;k<3;k++){let l=[...center],h=[...center];l[k]-=r*1.2;h[k]+=r*1.2;const a=project({x:l[0],y:l[1],z:l[2]}),b=project({x:h[0],y:h[1],z:h[2]});line(a.x,a.y,b.x,b.y,'#999',1);ctx.fillStyle='#333';ctx.fillText(['x','y','z'][k],b.x+5,b.y-5);}
const segments=[];for(let i=1;i<curve.data.length;i++){const p=curve.data[i-1],q=curve.data[i];if(!curve.valid(p)||!curve.valid(q))continue;const a=project(p),b=project(q);if(Math.hypot(a.x-b.x,a.y-b.y)<Math.max(W,H)*.6)segments.push({a,b,depth:(a.depth+b.depth)/2});}segments.sort((a,b)=>a.depth-b.depth);for(const {a,b,depth} of segments){const light=Math.max(28,Math.min(64,46+depth/r*9));line(a.x,a.y,b.x,b.y,`hsl(216 78% ${light}%)`,2.6);}
if($('showpoints').checked)for(const g of activeGroups){const p=project(g);if(p.x<0||p.x>W||p.y<0||p.y>H)continue;ctx.beginPath();ctx.arc(p.x,p.y,3.5,0,Math.PI*2);ctx.fillStyle='#087c83';ctx.fill();pointHits.push({x:p.x,y:p.y,t:g.branches[0].t});if($('pointlabels').checked){ctx.fillStyle='#111';ctx.fillText(g.label,p.x+6,p.y-6);}}
const param=selectedT??curve.a+(curve.b-curve.a)*Number($('position').value)/10000,p=curve.point(param),g=CurveGeometry.at(curve,param),q=project(p);$('tvalue').textContent=fmt(param);typeset($('tvalue'));if(curve.valid(p)){ctx.beginPath();ctx.arc(q.x,q.y,5,0,Math.PI*2);ctx.fillStyle='#c62855';ctx.fill();if($('tangent').checked&&g.T){const end=project({x:p.x+r*.7*g.T[0],y:p.y+r*.7*g.T[1],z:p.z+r*.7*g.T[2]});line(q.x,q.y,end.x,end.y,'#c45b16',2,[5,4]);}if($('frenet').checked)for(const [name,v,color] of [['T',g.T,'#c45b16'],['N',g.N,'#8c3ec0'],['B',g.B,'#087c83']]){if(!v)continue;const end=project({x:p.x+r*.55*v[0],y:p.y+r*.55*v[1],z:p.z+r*.55*v[2]});line(q.x,q.y,end.x,end.y,color,2);ctx.fillStyle=color;ctx.fillText(name,end.x+4,end.y);}}
$('metrics').textContent=`Điểm ≈ (${fmt(p.x)}; ${fmt(p.y)}; ${fmt(p.z)}). Các trục tham chiếu đi qua tâm khung nhìn; số liệu tọa độ xem tại đây và bảng.`;typeset($('metrics'));}
function previewFormulas(){const m=$('mode').value,variable=m==='cart'?'x':m==='polar'?'theta':'t';let cs;$('formula-preview').replaceChildren();try{cs=CurveMath.constants($('constants').value);$('constants').removeAttribute('aria-invalid');}catch(e){$('constants').setAttribute('aria-invalid','true');$('formula-preview').textContent=e.message;return;}const fields=m==='param'||m==='space'?['ex','ey',...(m==='space'?['ez']:[])]:['ey'];for(const id of fields){try{const parts=$(id).value.split('=');if(parts.length>2||m!=='implicit'&&parts.length>1)throw Error('Chỉ nhập một biểu thức trong ô này.');for(const part of parts)CurveMath.compile(part,m==='implicit'?['x','y']:variable,cs);$(id).removeAttribute('aria-invalid');}catch(e){$(id).setAttribute('aria-invalid','true');$('formula-preview').append(cell('p',`${id==='ex'?'x(t)':id==='ez'?'z(t)':$('ylabel').textContent}: ${e.message}`));}}}
const keySpecs=[['a/b','fraction'],['x²','square'],['xⁿ','power'],['√','sqrt'],['∛','cbrt'],['sin','sin'],['cos','cos'],['tan','tan'],['π','pi'],['( )','group']];const moreSpecs=['abs','exp','ln','log10','sinh','cosh','tanh','asin','acos','atan'].map(n=>[n,n]);
function insertMath(kind){const input=lastInput&&lastInput.offsetParent!==null?lastInput:$('ey'),start=input.selectionStart??input.value.length,end=input.selectionEnd??start,selected=input.value.slice(start,end),variable=$('mode').value==='cart'||$('mode').value==='implicit'?'x':$('mode').value==='polar'?'theta':'t';let text,offset,count;if(kind==='pi'){text='pi';offset=2;count=0;}else if(kind==='fraction'){text=`(${selected||'1'})/(1)`;offset=text.length-2;count=1;}else if(kind==='square'){text=`(${selected||variable})^2`;offset=selected?text.length:1;count=selected?0:variable.length;}else if(kind==='power'){text=`(${selected||variable})^(2)`;offset=text.length-2;count=1;}else if(kind==='group'){text=`(${selected||variable})`;offset=1;count=(selected||variable).length;}else{text=`${kind}(${selected||variable})`;offset=kind.length+1;count=(selected||variable).length;}input.setRangeText(text,start,end,'end');input.focus();input.setSelectionRange(start+offset,start+offset+count);input.dispatchEvent(new Event('input',{bubbles:true}));}
for(const [host,specs] of [['mathkeys',keySpecs],['morekeys',moreSpecs]])for(const [label,kind] of specs){const b=cell('button',label);b.type='button';b.setAttribute('aria-label','Chèn '+label);b.onmousedown=e=>e.preventDefault();b.onclick=()=>insertMath(kind);$(host).append(b);}
for(const id of ['ex','ey','ez','a','b','ymin','ymax','custompoints'])$(id).addEventListener('focus',()=>{lastInput=$(id);$('activefield').textContent='Đang nhập: '+(id==='ex'?'x(t)':id==='ey'?$('ylabel').textContent:id==='ez'?'z(t)':id==='a'?'cận đầu':id==='b'?'cận cuối':id);});
for(const id of ['ex','ey','ez','a','b','ymin','ymax','constants'])$(id).oninput=()=>{$('preset').value='custom';previewFormulas();clearTimeout(debounce);if($('auto').checked)debounce=setTimeout(build,650);else $('status').textContent='Công thức đã đổi. Bấm Vẽ để cập nhật.';};
const oldWheel=canvas.onwheel,oldDown=canvas.onpointerdown,oldMove=canvas.onpointermove,oldUp=canvas.onpointerup;let rotate=null;
canvas.onwheel=e=>{if(curve?.mode==='space'){e.preventDefault();camera.zoom=Math.max(.15,Math.min(8,camera.zoom*Math.exp(-e.deltaY*.001)));draw();}else oldWheel(e);};canvas.onpointerdown=e=>{if(curve?.mode==='space'){rotate={x:e.clientX,y:e.clientY,yaw:camera.yaw,pitch:camera.pitch};canvas.setPointerCapture(e.pointerId);}else oldDown(e);};canvas.onpointermove=e=>{if(rotate){camera.yaw=rotate.yaw+(e.clientX-rotate.x)*.008;camera.pitch=rotate.pitch+(e.clientY-rotate.y)*.008;draw();}else oldMove(e);};canvas.onpointerup=e=>{if(rotate){if(Math.hypot(e.clientX-rotate.x,e.clientY-rotate.y)<5){const r=canvas.getBoundingClientRect(),p=pointHits.find(p=>Math.hypot(p.x-e.clientX+r.left,p.y-e.clientY+r.top)<15);if(p)selectPoint(p.t);}rotate=null;}else oldUp(e);};canvas.onpointercancel=()=>{rotate=null;drag=null;};
for(const [id,yaw,pitch] of [['view-iso',.65,.5],['view-xy',0,0],['view-xz',0,-Math.PI/2],['view-yz',Math.PI/2,-Math.PI/2]])$(id).onclick=()=>{camera.yaw=yaw;camera.pitch=pitch;draw();};$('frenet').onchange=draw;
$('save').onclick=()=>{try{if(config().mode==='implicit')CurveAdvanced.implicit(config());else CurveMath.makeCurve(config());download(new Blob([JSON.stringify(config(),null,2)],{type:'application/json'}),'curvelab-bai.json');}catch(e){$('error').textContent=e.message;}};
function renderGuide(){const box=$('solution-guide');box.replaceChildren();const c=plotted,compact=s=>s.replace(/\s/g,'').replace(/\*\*/g,'^');let lines=[];
const eq=compact(c.y),x=compact(c.x);if(c.mode==='implicit'&&eq==='x^2+(y-cbrt(x^2))^2=1'||c.mode==='param'&&x==='cos(t)'&&eq==='sin(t)+cbrt(cos(t)^2)'){lines=['Bài 1.1.6 — hướng giải đã kiểm tra bằng thế vào phương trình.','Đặt x = cos t, y = sin t + ∛(cos²t), 0 ≤ t ≤ 2π. Khi đó x² + (y − ∛(x²))² = cos²t + sin²t = 1.','Có thể tách hai nhánh y = ∛(x²) ± √(1−x²), −1 ≤ x ≤ 1. Vết đối xứng qua Oy; không coi hai nhánh là một hàm y(x).','Đạo hàm của tham số hóa này không hữu hạn tại cos t = 0; đồ thị vẫn có thể vẽ, nhưng không dùng Frenet tại đó.'];if(c.mode==='implicit'){const btn=cell('button','Chuyển sang tham số hóa để khảo sát');btn.type='button';btn.onclick=()=>{$('mode').value='param';setMode();$('preset').value=String(presets.param.findIndex(r=>r[0].includes('1.1.6')));applyPreset();};box.append(btn);}}
else if(c.mode==='param'&&['cos(t)-sin(t)^2/sqrt(2)','cos(t)-(sin(t)^2)/sqrt(2)'].includes(x)&&eq==='sin(2t)/2'&&compact(c.a)==='-pi'&&compact(c.b)==='pi'){lines=['Bài 1.1.7 — đường con cá.','x′ = −sin t(1 + √2 cos t), y′ = cos(2t). Tốc độ v = |1 + √2 cos t| (√2 − cos t).','Tách tích phân tại t = −3π/4 và 3π/4 để bỏ dấu giá trị tuyệt đối. Độ dài trên [−π,π] là √2(π/2 + 3).','Tại ±3π/4, cả hai đạo hàm đều bằng 0: không dùng công thức Frenet có mẫu ‖γ′‖ tại đó.'];}
else if(c.mode==='space'&&x==='a*t'&&eq==='a*t^3/3'&&compact(c.z)==='a/(2t)'&&compact(c.a)==='1'&&compact(c.b)==='3'){lines=['Bài 1.1.10 — với a > 0.','Chọn x = at ⇒ y = at³/3, z = a/(2t). Hai mặt phẳng y=a/3 và y=9a cho t=1 và t=3.','γ′(t) = a(1, t², −1/(2t²)); ‖γ′(t)‖ = a√(1+t⁴+1/(4t⁴)) = a(t²+1/(2t²)).','L = a[t³/3 − 1/(2t)] từ 1 đến 3 = 9a. Thế tham số hóa vào cả hai phương trình để kiểm tra.'];if(!(curve.constants.a>0))lines.push('Hằng số a hiện tại không thỏa a > 0 của đề; công thức kết luận của bài chỉ áp dụng khi a > 0.');}
else if(c.mode==='param'&&x==='r*(t+sin(t))'&&eq==='r*(1-cos(t))'&&compact(c.a)==='0'&&compact(c.b)==='2*pi'){lines=['Bài 1.1.11 — theo đúng dấu sin(−t) trong đề, với r > 0.','γ(t) = r(t + sin t, 1 − cos t), γ′(t) = r(1 + cos t, sin t).','‖γ′(t)‖ = 2r|cos(t/2)|. Tách tích phân tại π: L trên [0,2π] = 8r.','γ′(t)=0 khi t=(2k+1)π, nên tham số hóa không chính quy tại các mốc đó. Với cycloid t−sin t, các mốc kỳ dị là 2kπ: hai quy ước khác nhau.'];if(!(curve.constants.r>0))lines.push('Hằng số r phải dương để đúng giả thiết bài.');}
else{lines=curve.implicit?['1. Xác định miền thực và các đối xứng của F(x,y)=0.','2. Thử tách nhánh y=f(x), hoặc tìm tham số hóa x(t), y(t). Bảng biến thiên chỉ áp dụng sau khi chọn được nhánh/tham số.','3. Hình đường mức là lấy mẫu: có thể bỏ sót thành phần rất nhỏ, điểm cô lập hoặc nghiệm bội.']:['1. Kiểm tra miền xác định và khoảng tham số; chú ý mẫu bằng 0, căn và logarit.','2. Tính γ′ và giải đồng thời các thành phần γ′=0 để xét chính quy. Điểm dừng của riêng x hoặc y không đủ kết luận kỳ dị.','3. Dùng bảng xét dấu từng tọa độ để mô tả vết; kiểm tra đầu/cuối, giao trục và khả năng tự cắt.','4. Độ dài: tích phân ‖γ′‖. Chỉ dùng κ, τ và khung Frenet tại nơi các mẫu số khác 0.','Đây là quy trình khảo sát, không phải lời giải tự động hay chứng minh cho biểu thức bất kỳ.'];}
for(const text of lines)box.append(cell('p',text));box.append(cell('p','Tham khảo: Trần Lê Nam (chủ biên) và cộng sự, Giáo trình Hình học vi phân, chương 1; bài 1.1.6, 1.1.10, 1.1.11. Chuyển sang mục Mặt cong 3D để khảo sát các đạo hàm riêng, dạng cơ bản và độ cong Gauss.'));
}

document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
function startCurveLab(){setMode();$('preset').value='0';resize();let loaded=false;try{const saved=localStorage.getItem('curvelab-v1');if(saved){restore(JSON.parse(saved));loaded=true;}}catch{}if(!loaded)build();new ResizeObserver(resize).observe(canvas);}

function exportCurveLatex(){if(!curve||!view&&curve.mode!=='space')throw Error('Cần vẽ một đường cong hợp lệ trước khi xuất.');const native=ctx,rec=new CurveTikZ.Recorder(W,H,native);try{rec.objectsOnly=true;ctx=rec;draw();}finally{ctx=native;}return rec.document({title:'Duong cong '+curve.mode,formula:null});}
$('latex-export').onclick=()=>{try{CurveTikZ.download(exportCurveLatex(),'curvelab-duong-cong.tex');$('status').textContent='Đã xuất TikZ chỉ gồm đối tượng, không kèm nền hoặc hệ trục. Biên dịch bằng XeLaTeX.';}catch(e){$('error').textContent='Không xuất được LaTeX: '+e.message;}};


$('png').objectExport=()=>{const native=ctx,out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const target=out.getContext('2d');target.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);target.objectsOnly=true;try{ctx=target;draw();}finally{ctx=native;draw();}out.toBlob(b=>b&&download(b,'curvelab-doi-tuong.png'));};