(()=>{'use strict';
const $=id=>document.getElementById(id),G=Construction,V=ConstructionView,canvas=$('board'),colors=['#1463d6','#b03587','#087e62','#c15a10','#783bb0'];
let ctx=canvas.getContext('2d');
const specs={hexahedron:['Khối sáu mặt · tám đỉnh',['Đáy A','Đáy B','Đáy C','Đáy D','Đỉnh E trên A','Đỉnh F trên B','Đỉnh G trên C','Đỉnh H trên D'],'Chọn hai vòng đỉnh tương ứng của khối lồi. Mỗi mặt gồm bốn điểm đồng phẳng.'],translateBy:['Tịnh tiến theo vectơ',['Điểm gốc','Gốc vectơ','Ngọn vectơ'],'Điểm ảnh dịch theo vectơ từ gốc đến ngọn và cập nhật khi kéo các điểm.'],select:['Chọn / di chuyển',[],'Bấm vào điểm hoặc đối tượng để chọn. Bấm đúp vào điểm tự do để sửa tọa độ. Kéo điểm để di chuyển.'],point:ConstructionSpecs.point,...ConstructionSpecs,prism:['Lăng trụ đáy tứ giác',['Đỉnh đáy A','Đỉnh đáy B','Đỉnh đáy C','Đỉnh đáy D','Đỉnh A′ tương ứng với A'],'Chọn bốn đỉnh quanh đáy lồi, rồi A′. Ba đỉnh tầng trên còn lại được dựng theo cùng vectơ AA′.']};
let dimension=location.hash==='#space'?3:2,objects=[],resolved=new Map(),editing=null,selected=null,selectedEdge=null,dialogPoint=null,lastInput=null,history=[],future=[],W=900,H=550,view={x:0,y:0,z:0,scale:65,yaw:.65,pitch:-.65,plane:'iso'},drag=null,activeSlot=0,labelHits=[],hits=[],occlusion={triangles:[],spheres:[]},markCount=0,showMarkup=false;
const fmt=v=>Number(v.toPrecision(7)).toString(),el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;},checked=id=>$(id).checked;
const displayKeys=['axes','grid','labels','marks','snap','hidden-lines','auto-build'];
const allowed=k=>dimension===2?!['plane','normal','planeFoot','sphere','tetrahedron','prism','hexahedron'].includes(k):!['perpendicular','perpBisector','circle','circlePoint','intersection'].includes(k);
const id=()=> 'o'+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const nameOf=id=>objects.find(o=>o.id===id)?.name||'?';
function nextName(kind){if(kind==='point'){for(const s of 'ABCDEFGHIJKLMNOPQRSTUVWXYZ')if(!objects.some(o=>o.name===s))return s;}const stem=kind==='point'?'P':['circle','circlePoint'].includes(kind)?'c':'d';let n=1;while(objects.some(o=>o.name===stem+n))n++;return stem+n;}
function snapshot(){return {app:'curvelab-construction',version:1,dimension,objects:structuredClone(objects),notes:$('notes').value,display:Object.fromEntries(displayKeys.map(k=>[k,checked(k)])),snapStep:$('snap-step').value};}
function captureDraft(){const k=$('tool').value||'select',fields={};for(const key of ['object-name',...specs[k][1].map((_,i)=>'ref-'+i),'coord-0','coord-1','coord-2','radius','angle','turn','base-direction','angle-plane','scale','shift-0','shift-1','shift-2','branch'])if($(key))fields[key]=$(key).value;return {tool:k,editing,activeSlot,fields};}
function applyDraft(d){$('tool').value=allowed(d.tool)?d.tool:'select';form(d.editing?objects.find(o=>o.id===d.editing):null);for(const [key,value] of Object.entries(d.fields)){const f=$(key);if(f){f.value=value;if(key.startsWith('ref-'))f.dataset.prior=value;}}activeSlot=Math.min(d.activeSlot,specs[$('tool').value][1].length);updateSteps();}
function actionSnapshot(){return {document:snapshot(),draft:captureDraft(),view:{...view},selected,selectedEdge,plane:$('placement-plane').value,level:$('placement-level').value};}
function historyUI(){for(const key of ['undo'])$(key).disabled=!history.length;for(const key of ['redo'])$(key).disabled=!future.length;}
function remember(){history.push(actionSnapshot());if(history.length>80)history.shift();future=[];historyUI();}
function restoreAction(s){restore(s.document);view={...s.view};$('placement-plane').value=s.plane;$('placement-level').value=s.level;$('level-label').textContent={xy:'z =',xz:'y =',yz:'x ='}[s.plane];applyDraft(s.draft);selected=objects.some(o=>o.id===s.selected)?s.selected:null;selectedEdge=s.selectedEdge??null;selectionUI();historyUI();draw();}
function undoAction(){if(!history.length)return;future.push(actionSnapshot());restoreAction(history.pop());}
function redoAction(){if(!future.length)return;history.push(actionSnapshot());restoreAction(future.pop());}
function maybeAutoBuild(){const k=$('tool').value;if(editing||!checked('auto-build')||['select','point'].includes(k)||nextSlot()<specs[k][1].length)return;try{submitObject();}catch(err){$('error').textContent=err.message;$('canvas-instruction').textContent=err.message+' · Sửa điểm đã chọn rồi dựng lại.';}}
function persist(){try{localStorage.setItem('curvelab-construction-'+dimension,JSON.stringify(snapshot()));}catch{}}
// Convert the old cube example's twelve independent edges into an explicit solid,
// preserving all point IDs and existing segment dependencies.
function upgradeLegacyCube(){if(dimension!==3||objects.some(o=>['prism','hexahedron'].includes(o.kind)))return;const points=[...'ABCDEFGH'].map(name=>objects.find(o=>o.name===name&&o.kind==='point'));if(points.some(p=>!p))return;const edges=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]],segments=edges.map(([a,b])=>objects.find(o=>o.kind==='segment'&&o.refs.includes(points[a].id)&&o.refs.includes(points[b].id)));if(segments.some(s=>!s))return;const solid={id:id(),name:'Khối ABCDEFGH',kind:'hexahedron',refs:points.map(p=>p.id)};if(G.solve([...objects,solid],3).get(solid.id).error)return;segments.forEach(s=>s.visible=false);objects.push(solid);}
function restore(doc){doc=G.importDocument(doc);dimension=doc.dimension;objects=structuredClone(doc.objects);upgradeLegacyCube();$('notes').value=typeof doc.notes==='string'?doc.notes.slice(0,6000):'';for(const k of displayKeys)$(k).checked=doc.display?.[k]??!['snap','auto-build'].includes(k);$('snap-step').value=['1','0.5','0.25','0.1'].includes(doc.snapStep)?doc.snapStep:'0.25';modeUI();window.history.replaceState(null,'',dimension===3?'#space':location.pathname);selected=null;selectedEdge=null;resolved=G.solve(objects,dimension);setTool('select');refresh();fit();}
function modeUI(){const space=dimension===3;$('heading').textContent=$('title').textContent=space?'Hình học không gian':'Hình học phẳng';$('nav2').setAttribute('aria-current',space?'false':'page');$('nav3').setAttribute('aria-current',space?'page':'false');$('views').hidden=$('work-plane').hidden=!space;$('grid-label').hidden=space;$('gesture').textContent=space?'Kéo nền để xoay · Shift + kéo để di chuyển · Cuộn để phóng to':'Kéo điểm để di chuyển · Kéo nền để di chuyển hình · Cuộn để phóng to';$('quick-input').placeholder=space?'A=(1,2,3); B=(4,0,2)':'A=(1,2); B=(4,0)';$('quick-help').textContent=(space?'Nhập A=(1,2,3)':'Nhập A=(1,2)')+'; nhiều điểm ngăn bằng dấu ;. Tên đã có sẽ cập nhật tọa độ.';$('tool').replaceChildren(...['select','point',...Object.keys(specs).filter(k=>!['select','point'].includes(k))].filter(allowed).map(k=>new Option(specs[k][0],k)));$('preset').replaceChildren(...(space?[['Tứ diện và hình chiếu','tetrahedron'],['Hình lập phương','cube'],['Mặt cầu tùy tâm','sphere'],['Bản vẽ trống','empty']]:[['Tam giác vuông 3–4–5','triangle'],['Đường thẳng và đường tròn','circle'],['Bản vẽ trống','empty']]).map(([s,v])=>new Option(s,v)));$('tool-shortcuts').replaceChildren();for(const [k,label] of [['select','↖ Chọn'],['point','• Điểm'],['segment','Đoạn thẳng'],['line','Đường thẳng'],['ray','Tia'],['fixedAngle','Góc biết số đo'],['triangle','Tam giác'],[space?'tetrahedron':'circlePoint',space?'Tứ diện':'Đường tròn'],['angle','Góc']]){const b=el('button',label);b.dataset.tool=k;b.onclick=()=>setTool(k);$('tool-shortcuts').append(b);}$('drawing-legend').replaceChildren();for(const [cls,txt] of space?[['visible-sample','Cạnh thấy'],['hidden-sample','Cạnh khuất · đổi theo góc quay']]:[['visible-sample','Hình dựng']]){const s=el('span'),i=el('i');i.className=cls;s.append(i,el('span',txt));$('drawing-legend').append(s);}}
function inputField(label,value,key){const l=el('label',label),e=el('input');e.value=String(value);e.id=key;e.dataset.math='';e.autocomplete='off';e.spellcheck=false;l.append(e);return l;}
function setTool(k){$('tool').value=k;selected=null;selectedEdge=null;form();selectionUI();draw();}
function form(o=null){lastInput=null;const k=o?.kind||$('tool').value,spec=specs[k];editing=o?.id||null;activeSlot=0;$('tool').value=k;$('tool').disabled=!!o;$('object-form').hidden=k==='select';$('steps-panel').hidden=k==='select';$('object-name').value=o?.name||nextName(k);$('tool-help').textContent=spec[2];$('fields').replaceChildren();$('math-panel').hidden=!['point','circle','sphere','transform','fixedAngle'].includes(k);if(k==='point'){const row=el('div');row.className='coordinate-fields';row.style.gridTemplateColumns=`repeat(${dimension},minmax(0,1fr))`;['x','y','z'].slice(0,dimension).forEach((a,i)=>row.append(inputField(a,o?.coords?.[i]??0,'coord-'+i)));$('fields').append(row);}else if(k!=='select'){const candidates=objects.filter(v=>v.id!==o?.id).filter(v=>acceptReference(k,resolved.get(v.id)));spec[1].forEach((label,i)=>{const l=el('label',`${i+1}. ${label}`),s=el('select');s.id='ref-'+i;s.required=true;s.append(new Option(['intersection','fixedAngle'].includes(k)?'Chọn trên hình hoặc trong danh sách…':'Bấm một điểm trên hình hoặc chọn ở đây…',''),...candidates.map(p=>new Option(p.name,p.id)));s.value=o?.refs[i]||'';s.dataset.prior=s.value;s.onfocus=()=>{activeSlot=i;updateSteps();};s.onchange=()=>{const value=s.value;s.value=s.dataset.prior;remember();s.value=value;s.dataset.prior=value;activeSlot=nextSlot();updateSteps();draw();maybeAutoBuild();};l.append(s);$('fields').append(l);});if(['circle','sphere'].includes(k))$('fields').append(inputField('Bán kính',o?.radius??2,'radius'));if(k==='intersection'){const l=el('label','Nhánh giao điểm'),s=el('select');s.id='branch';s.append(new Option('Giao điểm 1','0'),new Option('Giao điểm 2','1'));s.value=String(o?.branch||0);l.append(s);$('fields').append(l);}if(k==='fixedAngle')angleFields(o);if(k==='transform'){$('fields').append(inputField('Góc quay (độ)',o?.angle??0,'angle'),inputField('Tỉ số vị tự',o?.scale??1,'scale'));['x','y','z'].slice(0,dimension).forEach((a,i)=>$('fields').append(inputField('Tịnh tiến '+a,o?.translation?.[i]??0,'shift-'+i)));}}$('submit').textContent=o?'Lưu thay đổi':'Dựng '+(k==='point'?'điểm':spec[0].toLowerCase());$('cancel').hidden=!o;$('error').textContent='';updateSteps();}
function acceptReference(k,q){return k==='intersection'?['line','segment','ray','circle'].includes(q?.type):k==='fixedAngle'?['line','segment','ray'].includes(q?.type):q?.type==='point';}
function angleFields(o){$('fields').append(inputField('Số đo góc (độ) · 0 < α < 360',o?.angle??60,'angle'));const select=(label,id,items,value)=>{const l=el('label',label),s=el('select');s.id=id;s.append(...items.map(([text,v])=>new Option(text,v)));s.value=value;l.append(s);$('fields').append(l);};select('Hướng quay','turn',[['Ngược chiều kim đồng hồ','ccw'],['Cùng chiều kim đồng hồ','cw']],o?.turn||'ccw');select('Chiều cạnh gốc','base-direction',[['Thuận: đầu thứ nhất → đầu thứ hai','forward'],['Đảo: đầu thứ hai → đầu thứ nhất','reverse']],o?.baseDirection||'forward');if(dimension===3)select('Mặt phẳng qua đỉnh · hướng nhìn quy ước','angle-plane',[['Song song Oxy · nhìn từ +Oz','xy'],['Song song Oxz · nhìn từ −Oy','xz'],['Song song Oyz · nhìn từ +Ox','yz']],o?.anglePlane||'xy');$('fields').append(el('p','Đoạn thẳng: đảo chiều sẽ đổi đỉnh sang đầu còn lại. Tia / đường thẳng: giữ gốc, đảo hướng. Bật Ký hiệu tính chất để hiện cung góc và số đo. Nếu bật tự dựng, hãy nhập các tùy chọn trước khi chọn cạnh.','hint'));}
function nextSlot(){const n=specs[$('tool').value][1].length;for(let i=0;i<n;i++)if(!$('ref-'+i)?.value)return i;return n;}
function updateSteps(){const k=$('tool').value,spec=specs[k];$('steps').replaceChildren();let message=spec[2];if(k==='point'){message=editing?'Sửa các ô tọa độ rồi bấm Lưu thay đổi.':'Bấm vùng trống trên hình để đặt điểm, hoặc nhập tọa độ bên trái rồi bấm Dựng điểm.';for(const s of ['Đặt tên điểm hoặc giữ tên gợi ý.','Bấm vị trí trên hình; hoặc nhập tọa độ và bấm Dựng điểm.'])$('steps').append(el('li',s));}else if(k!=='select'){spec[1].forEach((s,i)=>{const value=$('ref-'+i)?.value,li=el('li',s+(value?' → '+nameOf(value):' → bấm chọn trên hình'));li.className=value?'done':i===activeSlot?'active':'';$('steps').append(li);});const last=el('li',k==='fixedAngle'?'Nhập số đo, chọn chiều cạnh và hướng quay; bấm Dựng hình (hoặc tự dựng khi chọn cạnh).':['circle','sphere'].includes(k)?checked('auto-build')&&!editing?'Tự dựng với bán kính đang nhập khi chọn đủ tâm.':'Nhập bán kính rồi bấm nút Dựng.':checked('auto-build')&&!editing?'Tự động dựng ngay khi chọn đủ điểm.':'Bấm nút Dựng để hoàn tất.');last.className=nextSlot()===spec[1].length?'active':'';$('steps').append(last);message=nextSlot()===spec[1].length?'Đã chọn đủ. '+last.textContent:`Bước ${activeSlot+1}/${spec[1].length}: ${spec[1][activeSlot]}. ${['fixedAngle','intersection'].includes(k)?'Bấm cạnh trên hình hoặc chọn trong danh sách.':'Bấm điểm có sẵn hoặc bấm vùng trống để tạo điểm mới.'}`;if(!objects.some(o=>resolved.get(o.id)?.type==='point'))message=k==='intersection'?'Cần dựng đường hoặc đường tròn trước khi tìm giao điểm.':'Bấm vùng trống trên hình để tạo và chọn điểm đầu tiên; không cần đổi công cụ.';}else message=dimension===3?'Kéo tên điểm để dời nhãn · Bấm cạnh để đổi màu · Bấm đúp điểm để sửa tọa độ · Kéo nền để xoay':'Kéo tên điểm để dời nhãn · Bấm cạnh để đổi màu · Bấm đúp điểm để sửa tọa độ · Kéo điểm để di chuyển';$('step-status').textContent=message;$('canvas-instruction').textContent=message;$('finish-build').hidden=['select','point'].includes(k);$('finish-build').disabled=nextSlot()<spec[1].length;$('finish-build').textContent=editing?'Lưu thay đổi':'Dựng hình';for(const b of $('tool-shortcuts').children)b.setAttribute('aria-pressed',String(b.dataset.tool===k));canvas.style.cursor=k==='select'?'grab':'crosshair';}
function describe(q){if(q.error)return q.error;if(q.type==='point')return '('+q.p.slice(0,dimension).map(fmt).join('; ')+')'+(q.kind!=='point'?' · '+specs[q.kind][0]:'');if(['circle','sphere'].includes(q.type))return (q.refs.length===1?'Tâm '+nameOf(q.refs[0])+' · ':'')+'r ≈ '+fmt(q.radius);if(q.kind==='fixedAngle')return 'Góc '+fmt(q.value)+'° · '+(q.turn==='cw'?'cùng':'ngược')+' chiều kim đồng hồ';if(q.type==='ray')return 'Tia · gốc '+nameOf(q.refs[0]);if(q.type==='segment')return 'Độ dài ≈ '+fmt(q.length);if(q.type==='angle')return '∠ ≈ '+fmt(q.value)+'°';if(q.type==='triangle')return 'Diện tích ≈ '+fmt(q.area)+' · Chu vi ≈ '+fmt(q.perimeter);if(['tetrahedron','prism','hexahedron'].includes(q.type))return 'Thể tích ≈ '+fmt(q.volume);return specs[q.kind]?.[0]+' · '+q.refs.map(nameOf).join(', ');}
function baseColor(o){return o.color||colors[objects.indexOf(o)%colors.length];}
function edgeHit(p,id){return hits.filter(h=>h.id===id&&h.edge!==null).map(h=>({...h,d:distance(p,h.a,h.b)})).filter(h=>h.d<8).sort((a,b)=>a.d-b.d)[0];}
function selectionUI(){const o=objects.find(o=>o.id===selected);$('selection-panel').hidden=!o;if(o){$('selection-title').textContent=o.name+(selectedEdge!==null?' · cạnh '+(selectedEdge+1):'');$('selection-color').value=(selectedEdge!==null?o.edgeColors?.[selectedEdge]:null)||baseColor(o);$('selection-color-label').textContent=selectedEdge!==null?'Màu cạnh đã chọn':'Màu đối tượng';$('selection-description').textContent=describe(resolved.get(o.id));$('edit-selected').textContent=o.kind==='point'?'Sửa tọa độ':'Sửa đối tượng';}for(const row of $('objects').children)row.className='object-row'+(row.dataset.id===selected?' selected':'')+(resolved.get(row.dataset.id)?.error?' invalid':'');}
function refresh(){resolved=G.solve(objects,dimension);$('objects').replaceChildren();$('measurements').replaceChildren();let errors=0;for(const o of objects){const q=resolved.get(o.id),row=el('div');row.className='object-row';row.dataset.id=o.id;const check=el('input');check.type='checkbox';check.checked=o.visible!==false;check.setAttribute('aria-label','Hiện '+o.name);check.onchange=()=>{remember();o.visible=check.checked;refresh();};const desc=el('div'),name=el('button',o.name);name.type='button';name.className='object-name';name.onclick=()=>chooseObject(o.id);desc.append(name,el('small',describe(q)));const actions=el('div');actions.className='object-actions';const edit=el('button','Sửa'),del=el('button','×');edit.setAttribute('aria-label','Sửa '+o.name);edit.onclick=()=>editObject(o.id);del.setAttribute('aria-label','Xóa '+o.name);del.onclick=()=>{const depend=objects.filter(p=>p.refs.includes(o.id));if(depend.length){$('error').textContent='Xóa đối tượng phụ thuộc trước: '+depend.map(p=>p.name).join(', ')+'.';return;}remember();objects=objects.filter(p=>p.id!==o.id);selected=null;selectedEdge=null;refresh();form();};actions.append(edit,del);row.append(check,desc,actions);$('objects').append(row);if(q.error)errors++;if(!['point','line'].includes(q.type)&&!q.error){const item=el('div');item.className='result-item';const label=el('span',o.name+' · '+specs[o.kind][0]);label.className='result-label';item.append(label,el('strong',describe(q)));$('measurements').append(item);}}$('count').textContent='('+objects.length+')';historyUI();$('status').textContent=errors?errors+' đối tượng chưa xác định; xem giải thích trong danh sách.':objects.length+' đối tượng. Các phép dựng cập nhật theo điểm gốc.';selectionUI();draw();persist();}
function commit(o){if(!o.name.trim())throw Error('Nhập tên đối tượng.');if(objects.some(p=>p.id!==o.id&&p.name===o.name))throw Error('Tên đã được sử dụng.');if(!objects.some(p=>p.id===o.id)&&objects.length>=300)throw Error('Tối đa 300 đối tượng.');const next=G.order(objects.some(p=>p.id===o.id)?objects.map(p=>p.id===o.id?o:p):[...objects,o]),q=G.solve(next,dimension).get(o.id);if(q.error)throw Error(q.error);remember();objects=next;selected=o.id;selectedEdge=null;refresh();}
function submitObject(){const kind=$('tool').value;if(kind==='select')return;const old=objects.find(o=>o.id===editing),o={...old,id:editing||id(),kind,name:$('object-name').value.trim(),refs:specs[kind][1].map((_,i)=>$('ref-'+i).value)};if(kind==='point')o.coords=[0,1,2].map(i=>i<dimension?$('coord-'+i).value:'0');if(['circle','sphere'].includes(kind))o.radius=$('radius').value;if(kind==='fixedAngle'){o.angle=$('angle').value;o.turn=$('turn').value;o.baseDirection=$('base-direction').value;o.anglePlane=dimension===3?$('angle-plane').value:'xy';}if(kind==='intersection')o.branch=Number($('branch').value);if(kind==='transform'){o.angle=$('angle').value;o.scale=$('scale').value;o.translation=[0,1,2].map(i=>i<dimension?$('shift-'+i).value:'0');}commit(o);const message='Đã dựng '+o.name+'.';form();$('status').textContent=message;}
function chooseObject(key,record=true){const q=resolved.get(key),k=$('tool').value;if(!q||q.error)return;selected=key;selectedEdge=null;const n=specs[k][1].length;if(k!=='select'&&k!=='point'&&n){if(!acceptReference(k,q)){$('error').textContent=['intersection','fixedAngle'].includes(k)?'Chọn một đường thẳng, đoạn thẳng hoặc tia'+(k==='intersection'?' hoặc đường tròn.':'.'):'Công cụ này cần chọn điểm.';return;}if(activeSlot>=n)activeSlot=0;const field=$('ref-'+activeSlot);if(!Array.from(field.options).some(o=>o.value===key)){$('error').textContent='Không thể dùng chính đối tượng đang sửa làm tham chiếu.';return;}if(field.value===key)return;if(record)remember();field.value=key;field.dataset.prior=key;activeSlot=nextSlot();$('error').textContent='';updateSteps();}selectionUI();draw();maybeAutoBuild();}
function editObject(key){const o=objects.find(o=>o.id===key);if(!o)return;selected=key;selectedEdge=null;if(o.kind==='point'){dialogPoint=key;$('point-dialog-title').textContent='Sửa tọa độ điểm '+o.name;$('dialog-name').value=o.name;$('dialog-coordinates').replaceChildren();$('dialog-coordinates').style.gridTemplateColumns=`repeat(${dimension},minmax(0,1fr))`;['x','y','z'].slice(0,dimension).forEach((a,i)=>$('dialog-coordinates').append(inputField(a,o.coords[i],'dialog-'+i)));$('dialog-error').textContent='';$('point-dialog').showModal();$('dialog-0').focus();}else{form(o);$('object-name').focus();$('object-name').scrollIntoView({block:'nearest'});if(resolved.get(key)?.type==='point')$('error').textContent='Điểm này được dựng từ các điểm khác. Sửa điểm tham chiếu; tọa độ được tính tự động.';}selectionUI();draw();}
function quickPoints(source){const draft=captureDraft(),entries=source.split(';').map(s=>s.trim()).filter(Boolean);if(!entries.length)throw Error('Nhập ví dụ '+(dimension===2?'A=(1,2)':'A=(1,2,3)')+'.');let next=structuredClone(objects),names=new Set(),last=null;for(const entry of entries){const match=entry.match(/^([^=()\s]{1,40})\s*=\s*\((.*)\)\s*$/);if(!match)throw Error('Cú pháp: A=(1,2); B=(3,4). Trong 3D cần ba tọa độ.');const name=match[1];if(names.has(name))throw Error('Tên '+name+' bị lặp trong cùng lần nhập.');names.add(name);const coords=[];let depth=0,start=0;for(let i=0;i<match[2].length;i++){const c=match[2][i];if(c==='(')depth++;if(c===')')depth--;if(depth<0)throw Error('Ngoặc không khớp.');if(c===','&&depth===0){coords.push(match[2].slice(start,i).trim());start=i+1;}}coords.push(match[2].slice(start).trim());if(depth!==0||coords.length!==dimension||coords.some(s=>!s))throw Error('Điểm '+name+' cần '+dimension+' tọa độ, ngăn bằng dấu phẩy.');coords.forEach(G.number);if(dimension===2)coords.push('0');const old=next.find(o=>o.name===name);if(old&&old.kind!=='point')throw Error(name+' là đối tượng phụ thuộc; hãy đổi tên điểm hoặc sửa điểm gốc.');last={...old,id:old?.id||id(),kind:'point',name,refs:[],coords};if(old)next=next.map(o=>o.id===old.id?last:o);else next.push(last);}if(next.length>300)throw Error('Tối đa 300 đối tượng.');remember();objects=next;selected=last.id;selectedEdge=null;refresh();if(specs[draft.tool][1].length)applyDraft(draft);else form();$('status').textContent='Đã nhập / cập nhật '+entries.length+' điểm.';return entries.length;}
function project(p){if(dimension===2)return [W/2+(p[0]-view.x)*view.scale,H/2-(p[1]-view.y)*view.scale];const q=V.camera(p,view);return [W/2+q[0]*view.scale,H/2-q[1]*view.scale];}
function stroke(points,color='#1463d6',width=1.6,dash=[],closed=false,fill=null){if(points.some(p=>!p.every(Number.isFinite)))return;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));if(closed)ctx.closePath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);if(fill){ctx.fillStyle=fill;ctx.fill();}ctx.stroke();ctx.setLineDash([]);}
function path(points,color,width=1.6,dash=[],closed=false,fill=null,key=null,selfSphere=null,edgeBase=null){const projected=points.map(project);if(fill)stroke(projected,color,0,[],closed,fill);const count=closed?points.length:points.length-1;for(let i=0;i<count;i++){const a=points[i],b=points[(i+1)%points.length],pa=projected[i],pb=projected[(i+1)%points.length];const edge=edgeBase===null?null:edgeBase+i,owner=objects.find(o=>o.id===key),custom=edge!==null?owner?.edgeColors?.[edge]:owner?.color,ink=custom||color,w=ctx.objectsOnly!==true&&selected===key&&selectedEdge!==null?(selectedEdge===edge?3:1.8):width;if(key)hits.push({id:key,edge,a:pa,b:pb});if(dimension===3&&checked('hidden-lines'))for(const r of V.split(a,b,view,selfSphere?{...occlusion,spheres:occlusion.spheres.filter(s=>s.id!==selfSphere.id)}:occlusion)){const behind=r.hidden||(selfSphere&&V.camera(G.mul(G.add(r.a,r.b),.5),view)[2]<V.camera(selfSphere.c,view)[2]-1e-7);stroke([project(r.a),project(r.b)],behind?(custom||'#8290a0'):ink,behind?1.2:w,behind?[5,4]:dash);}else stroke([pa,pb],ink,w,dash);}}
const LABEL_RADIUS=56;
function labelOffset(o){const p=o?.labelOffset;if(!Array.isArray(p)||p.length!==2||!p.every(Number.isFinite))return [9,-9];const length=Math.hypot(...p);return length>LABEL_RADIUS?p.map(v=>v*LABEL_RADIUS/length):p;}
function hitLabel(p){if($('tool').value!=='select'||!checked('labels'))return null;return labelHits.filter(h=>Math.hypot(p[0]-h.point[0],p[1]-h.point[1])>8&&p[0]>=h.x-3&&p[0]<=h.x+h.width+3&&p[1]>=h.y-16&&p[1]<=h.y+4).sort((a,b)=>Math.hypot(p[0]-a.x,p[1]-a.y)-Math.hypot(p[0]-b.x,p[1]-b.y))[0];}
function drawRay(a,d,color,width,key){
 const origin=project(a),v=G.sub(project(G.add(a,d)),origin),length=Math.hypot(...v);if(length<1e-8)return;
 const dir=v.map(x=>x/length);let lo=0,hi=Infinity;
 for(let axis=0;axis<2;axis++){const min=12,max=(axis?H:W)-12;if(Math.abs(dir[axis])<1e-10){if(origin[axis]<min||origin[axis]>max)return;continue;}const t1=(min-origin[axis])/dir[axis],t2=(max-origin[axis])/dir[axis];lo=Math.max(lo,Math.min(t1,t2));hi=Math.min(hi,Math.max(t1,t2));}
 if(hi<lo||!Number.isFinite(hi))return;
 const first=G.add(a,G.mul(d,lo/length)),last=G.add(a,G.mul(d,hi/length));path([first,last],color,width,[],false,null,key);
 const tip=origin.map((v,i)=>v+dir[i]*hi),back=tip.map((v,i)=>v-dir[i]*10),side=[-dir[1]*4,dir[0]*4],behind=dimension===3&&checked('hidden-lines')&&V.hidden(V.camera(last,view),occlusion);
 stroke([G.add(back,side),tip,G.sub(back,side)],behind?(objects.find(o=>o.id===key)?.color||'#8290a0'):color,width);
}
function drawFixedAngle(q,color){markCount++;if(!showMarkup)return;const radius=30/view.scale,at=t=>G.add(q.a,G.mul(G.add(G.mul(q.u,Math.cos(t)),G.mul(q.tangent,Math.sin(t))),radius));if(Math.abs(q.value-90)<1e-9)rightMark(G.add(q.a,q.u),q.a,G.add(q.a,q.d),color);else path(Array.from({length:Math.max(16,Math.ceil(q.value/4))+1},(_,i)=>at(q.theta*i/Math.max(16,Math.ceil(q.value/4)))),color,1.8);const pos=project(G.add(q.a,G.mul(G.sub(at(q.theta/2),q.a),1.55)));ctx.fillStyle=color;ctx.font='13px system-ui';ctx.fillText(fmt(q.value)+'°',pos[0],pos[1]);}
function point(p,label,color,key){const q=project(p),chosen=ctx.objectsOnly!==true&&(selected===key||specs[$('tool').value][1].some((_,i)=>$('ref-'+i)?.value===key)),isHidden=dimension===3&&checked('hidden-lines')&&V.hidden(V.camera(p,view),occlusion);ctx.beginPath();ctx.arc(...q,chosen?8:5,0,2*Math.PI);ctx.fillStyle=isHidden?'white':color;ctx.fill();ctx.strokeStyle=chosen?'#e28a18':color;ctx.lineWidth=chosen?2.5:1.3;ctx.stroke();if(checked('labels')){ctx.font='bold 15px Georgia';ctx.fillStyle=isHidden?'#798391':color;const offset=labelOffset(objects.find(o=>o.id===key)),x=q[0]+offset[0],y=q[1]+offset[1];ctx.fillText(label,x,y);labelHits.push({id:key,point:q,x,y,width:ctx.measureText(label)?.width||label.length*9});}}
function rightMark(a,b,c,color){if(G.norm(G.sub(a,b))<1e-9||G.norm(G.sub(c,b))<1e-9)return;const u=G.unit(G.sub(a,b)),v=G.unit(G.sub(c,b));if(Math.abs(G.dot(u,v))>1e-7)return;markCount++;if(!showMarkup)return;const size=Math.min(14/view.scale,G.norm(G.sub(a,b))*.2,G.norm(G.sub(c,b))*.2);path([G.add(b,G.mul(u,size)),G.add(b,G.mul(G.add(u,v),size)),G.add(b,G.mul(v,size))],color,1.8);}
function arcMark(a,b,c,color,forceArc=false){if(G.norm(G.sub(a,b))<1e-9||G.norm(G.sub(c,b))<1e-9)return;const u=G.unit(G.sub(a,b)),v=G.unit(G.sub(c,b)),theta=Math.acos(Math.max(-1,Math.min(1,G.dot(u,v))));if(!forceArc&&Math.abs(theta-Math.PI/2)<1e-7){rightMark(a,b,c,color);return;}if(theta<1e-8||Math.PI-theta<1e-8)return;markCount++;if(!showMarkup)return;const w=G.unit(G.sub(v,G.mul(u,G.dot(u,v)))),r=Math.min(26/view.scale,G.norm(G.sub(a,b))*.25,G.norm(G.sub(c,b))*.25);path(Array.from({length:25},(_,i)=>G.add(b,G.mul(G.add(G.mul(u,Math.cos(theta*i/24)),G.mul(w,Math.sin(theta*i/24))),r))),color,1.8);}
function triangleMarks(ps,color){ps.forEach((p,i)=>rightMark(ps[(i+1)%3],p,ps[(i+2)%3],color));const lengths=ps.map((p,i)=>G.norm(G.sub(p,ps[(i+1)%3])));for(let i=0;i<3;i++)if(lengths.some((l,j)=>i!==j&&Math.abs(l-lengths[i])<1e-7*Math.max(1,l))){markCount++;if(!showMarkup)continue;const a=project(ps[i]),b=project(ps[(i+1)%3]),d=[b[0]-a[0],b[1]-a[1]],n=Math.hypot(...d),m=[(a[0]+b[0])/2,(a[1]+b[1])/2];if(n>1)stroke([[m[0]-d[1]/n*5,m[1]+d[0]/n*5],[m[0]+d[1]/n*5,m[1]-d[0]/n*5]],color,1.8);}}
function ring(c,r,n,color,key,selfSphere=null){if(dimension===2){const p=project(c),radius=r*view.scale;ctx.beginPath();ctx.ellipse(p[0],p[1],radius,radius,0,0,2*Math.PI);ctx.strokeStyle=color;ctx.lineWidth=selected===key?3:1.8;ctx.setLineDash([]);ctx.stroke();for(let i=0;i<120;i++){const at=t=>[p[0]+radius*Math.cos(t),p[1]+radius*Math.sin(t)];hits.push({id:key,edge:null,a:at(i*Math.PI/60),b:at((i+1)*Math.PI/60)});}return;}const u=G.unit(G.cross(n,Math.abs(n[2])<.9?[0,0,1]:[0,1,0])),v=G.cross(n,u);path(Array.from({length:121},(_,i)=>G.add(c,G.mul(G.add(G.mul(u,Math.cos(i*Math.PI/60)),G.mul(v,Math.sin(i*Math.PI/60))),r))),color,selected===key?3:1.8,[],false,null,key,selfSphere);}
function axes(){const span=Math.max(W,H)/view.scale;if(dimension===2){const raw=span/12,base=10**Math.floor(Math.log10(raw)),step=[1,2,5,10].map(x=>x*base).find(x=>x>=raw);ctx.font='12px system-ui';ctx.fillStyle='#777';const origin=project([0,0,0]);for(let axis=0;axis<2;axis++){const mid=axis?view.y:view.x;for(let k=Math.ceil((mid-span)/step);k*step<=mid+span;k++){const p=project(axis?[0,k*step,0]:[k*step,0,0]);if(checked('grid'))stroke(axis?[[0,p[1]],[W,p[1]]]:[[p[0],0],[p[0],H]],'#edf0f2',1);if(checked('axes')&&k)ctx.fillText(fmt(k*step),axis?Math.min(W-40,Math.max(5,origin[0]+5)):p[0]+3,axis?p[1]-3:Math.min(H-5,Math.max(14,origin[1]+14)));}}if(checked('axes')){stroke([[0,origin[1]],[W,origin[1]]],'#555');stroke([[origin[0],0],[origin[0],H]],'#555');ctx.fillText('x',W-16,Math.min(H-5,Math.max(14,origin[1]-7)));ctx.fillText('y',Math.min(W-15,Math.max(5,origin[0]+7)),18);}}else if(checked('axes'))for(let i=0;i<3;i++){const a=[0,0,0],b=[0,0,0];a[i]=-span/2;b[i]=span/2;stroke([project(a),project(b)],'#aaa',1);const q=project(b);ctx.fillStyle='#555';ctx.font='15px Georgia';ctx.fillText('xyz'[i],q[0]+5,q[1]-5);const raw=span/10,base=10**Math.floor(Math.log10(raw)),step=[1,2,5,10].map(x=>x*base).find(x=>x>=raw);const pa=project(a),pb=project(b),length=Math.hypot(pb[0]-pa[0],pb[1]-pa[1]);if(length>35){const nx=-(pb[1]-pa[1])/length,ny=(pb[0]-pa[0])/length;ctx.font='12px system-ui';for(let t=Math.ceil(-span/2/step)*step;t<span/2;t+=step){if(Math.abs(t)<step*.01)continue;const p=[0,0,0];p[i]=t;const r=project(p);stroke([[r[0]-3*nx,r[1]-3*ny],[r[0]+3*nx,r[1]+3*ny]],'#777',1);ctx.fillText(fmt(t),r[0]+7*nx,r[1]+7*ny);}} }}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='white';if(ctx.objectsOnly!==true)ctx.fillRect(0,0,W,H);hits=[];labelHits=[];markCount=0;showMarkup=checked('marks');occlusion=dimension===3?V.scene([...resolved.values()],view):{triangles:[],spheres:[]};if(ctx.objectsOnly!==true)axes();let idx=0;for(const o of objects){const q=resolved.get(o.id),color=baseColor(o);if(!q||q.error||o.visible===false||q.type==='point')continue;const refs=o.refs.map(id=>resolved.get(id)?.p),width=ctx.objectsOnly!==true&&selected===o.id?3:1.8;switch(q.type){case 'ray':drawRay(q.a,q.d,color,width,o.id);if(q.kind==='fixedAngle')drawFixedAngle(q,color);break;case 'segment':path([q.a,q.b],color,width,[],false,null,o.id);break;case 'line':{const extent=Math.max(W,H)/view.scale*2,anchor=[view.x,view.y,view.z],t=G.dot(G.sub(anchor,q.a),q.d),a=G.add(q.a,G.mul(q.d,t));path([G.add(a,G.mul(q.d,-extent)),G.add(a,G.mul(q.d,extent))],color,width,[],false,null,o.id);if(q.kind==='bisector'){const middle=G.add(refs[1],G.mul(q.d,Math.min(G.norm(G.sub(refs[0],refs[1])),G.norm(G.sub(refs[2],refs[1])))));arcMark(refs[0],refs[1],middle,color,true);arcMark(middle,refs[1],refs[2],color,true);}if(q.kind==='perpendicular')rightMark(G.add(q.a,q.d),q.a,G.add(q.a,G.sub(refs[2],refs[1])),color);break;}case 'circle':ring(q.c,q.radius,q.normal,color,o.id);break;case 'sphere':for(const n of [[0,0,1],[0,1,0],[1,0,0]])ring(q.c,q.radius,n,color,o.id,q);ring(q.c,q.radius,V.direction(view),color,o.id,q);break;case 'triangle':path(q.p,color,width,[],true,null,o.id,null,0);triangleMarks(q.p,color);break;case 'plane':path(V.faces(q)[0],color,1,[],true,null,o.id,null,0);break;case 'tetrahedron':case 'prism':case 'hexahedron':V.edges(q).forEach((edge,i)=>path(edge,color,width,[],false,null,o.id,null,i));for(const f of V.faces(q))if(f.length===3)triangleMarks(f,color);else f.forEach((p,i)=>rightMark(f[(i+3)%4],p,f[(i+1)%4],color));break;case 'angle':path(q.p,color,1,[],false,null,o.id);arcMark(...q.p,color);if(showMarkup){const p=project(q.p[1]);ctx.fillStyle=color;ctx.font='13px system-ui';ctx.fillText(fmt(q.value)+'°',p[0]+26,p[1]+24);}break;}}
idx=0;for(const o of objects){const q=resolved.get(o.id),color=baseColor(o);if(q?.type!=='point'||q.error||o.visible===false)continue;if(['foot','planeFoot'].includes(o.kind)){const a=resolved.get(o.refs[0]).p;path([a,q.p],color,1.3,[],false,null,o.id);const b=resolved.get(o.refs[1]).p,c=resolved.get(o.refs[2]).p;const direction=o.kind==='planeFoot'?G.add(q.p,G.sub(c,b)):G.norm(G.sub(b,q.p))>1e-9?b:c;rightMark(a,q.p,direction,color);}point(q.p,o.name,color,o.id);}$('marks-info').textContent=markCount?(showMarkup?'Đang hiện ':'Đang ẩn ')+markCount+' dấu tính chất trên hình.':'Hình hiện tại chưa có góc / cạnh thỏa điều kiện để đánh dấu. Dùng công cụ Góc hoặc dựng đường vuông góc, phân giác.';$('snap-info').textContent=checked('snap')?'Khi đặt / kéo điểm, tọa độ làm tròn theo bước '+$('snap-step').value.replace('.',',')+'. Nhập bàn phím vẫn giữ nguyên.':'Đang kéo / đặt điểm tự do; tọa độ không được làm tròn theo lưới.';}
function resize(){const r=canvas.getBoundingClientRect();W=r.width;H=r.height;const dpr=Math.min(2,devicePixelRatio||1);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
function fit(){const ps=[];for(const q of resolved.values()){if(q.error||q.visible===false)continue;if(q.type==='point')ps.push(q.p);if(['circle','sphere'].includes(q.type))for(let i=0;i<3;i++)for(const s of [-1,1]){const p=[...q.c];p[i]+=s*q.radius;ps.push(p);}if(['prism','tetrahedron','hexahedron'].includes(q.type))ps.push(...q.p);}if(!ps.length){view.x=view.y=view.z=0;view.scale=60;draw();return;}const ranges=[0,1,2].map(i=>[Math.min(...ps.map(p=>p[i])),Math.max(...ps.map(p=>p[i]))]);[view.x,view.y,view.z]=ranges.map(r=>(r[0]+r[1])/2);view.scale=Math.min(W,H)/(Math.max(3,...ranges.map(r=>r[1]-r[0]))*1.65);draw();}
function preset(kind){objects=[];const p=(name,coords)=>{const o={id:id(),name,kind:'point',coords:coords.map(String),refs:[]};objects.push(o);return o.id;},o=(name,kind,refs,extra={})=>{const key=id();objects.push({id:key,name,kind,refs,...extra});return key;};if(kind==='triangle'){const a=p('A',[0,0,0]),b=p('B',[4,0,0]),c=p('C',[0,3,0]);o('ABC','triangle',[a,b,c]);o('Phân giác A','bisector',[b,a,c]);o('I','incenter',[a,b,c]);o('Nội tiếp','incircle',[a,b,c]);o('Góc A','angle',[b,a,c]);}else if(kind==='circle'){const a=p('A',[-3,-1,0]),b=p('B',[4,1,0]),m=p('M',[1,1,0]);const d=o('d','line',[a,b]),c=o('c','circle',[m],{radius:'2'});o('H','foot',[m,a,b]);o('I₁','intersection',[d,c],{branch:0});o('I₂','intersection',[d,c],{branch:1});}else if(kind==='tetrahedron'){const a=p('A',[0,0,0]),b=p('B',[4,0,0]),c=p('C',[0,3,0]),s=p('S',[1,1,4]);o('SABC','tetrahedron',[s,a,b,c]);o('H','planeFoot',[s,a,b,c]);}else if(kind==='sphere'){const m=p('M',[1,2,1]);o('Mặt cầu M','sphere',[m],{radius:'2'});}else if(kind==='cube'){const a=p('A',[0,0,0]),b=p('B',[3,0,0]),c=p('C',[3,3,0]),d=p('D',[0,3,0]),e=p('E',[0,0,3]);o('ABCDEFGH','prism',[a,b,c,d,e]);for(const [name,ref] of [['F',b],['G',c],['H',d]])o(name,'translateBy',[ref,a,e]);}selected=null;selectedEdge=null;refresh();setTool('select');fit();}
function local(e){const r=canvas.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top];}
function distance(p,a,b){const d=G.sub(b,a),n=G.dot(d,d),t=n?Math.max(0,Math.min(1,G.dot(G.sub(p,a),d)/n)):0;return G.norm(G.sub(p,G.add(a,G.mul(d,t))));}
function hitAt(p,pointsOnly=false){let candidates=objects.filter(o=>o.visible!==false&&resolved.get(o.id)?.type==='point'&&!resolved.get(o.id).error).map(o=>({o,d:G.norm(G.sub(project(resolved.get(o.id).p),p)),z:dimension===3?V.camera(resolved.get(o.id).p,view)[2]:0})).filter(x=>x.d<=14).sort((a,b)=>a.d-b.d||b.z-a.z);if(candidates.length&&!(['intersection','fixedAngle'].includes($('tool').value)&&!pointsOnly))return candidates[0].o.id;if(pointsOnly)return null;const lines=hits.filter(h=>!['fixedAngle','intersection'].includes($('tool').value)||acceptReference($('tool').value,resolved.get(h.id))).map(h=>({...h,d:distance(p,h.a,h.b)})).filter(h=>h.d<8).sort((a,b)=>a.d-b.d);return lines[0]?.id||null;}
function mousePoint(p,original=null){let q;if(dimension===2)q=[view.x+(p[0]-W/2)/view.scale,view.y-(p[1]-H/2)/view.scale,0];else{const plane=$('placement-plane').value,axis={xy:2,xz:1,yz:0}[plane],level=original?original[axis]:G.number($('placement-level').value);q=V.fromScreen(...p,view,W,H,plane,level);}const fixed=dimension===2?2:{xy:2,xz:1,yz:0}[$('placement-plane').value],step=Number($('snap-step').value)||.25;return q.map((v,i)=>i===fixed?v:checked('snap')?Math.round(v/step)*step:Number(v.toPrecision(10)));}
function canvasClick(p){const k=$('tool').value,pointTool=!['select','intersection','fixedAngle'].includes(k),hit=hitAt(p,pointTool);if(hit){chooseObject(hit);if(k==='select'){selectedEdge=edgeHit(p,hit)?.edge??null;selectionUI();draw();}return;}if(pointTool&&(k!=='point'||!editing)){if(k!=='point'&&nextSlot()===specs[k][1].length&&activeSlot>=specs[k][1].length){$('canvas-instruction').textContent='Đã đủ điểm. Bấm Dựng hình, hoặc chọn lại một bước bên trái để đổi điểm.';return;}const q=mousePoint(p),draft=captureDraft(),o={id:id(),name:k==='point'?$('object-name').value.trim()||nextName('point'):nextName('point'),kind:'point',coords:q.map(String),refs:[]};commit(o);if(k==='point')form();else{applyDraft(draft);chooseObject(o.id,false);}}else{selected=null;selectedEdge=null;selectionUI();draw();}}

function download(blob,name){const a=el('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
$('tool').onchange=()=>setTool($('tool').value);$('cancel').onclick=()=>setTool('select');$('reset-picks').onclick=()=>{remember();form();draw();};$('object-form').onsubmit=e=>{e.preventDefault();try{submitObject();}catch(err){$('error').textContent=err.message;}};
$('finish-build').onclick=()=>{try{submitObject();}catch(err){$('error').textContent=err.message;$('canvas-instruction').textContent=err.message;}};
$('quick-form').onsubmit=e=>{e.preventDefault();try{quickPoints($('quick-input').value);$('quick-input').value='';$('quick-error').textContent='';}catch(err){$('quick-error').textContent=err.message;}};
$('point-edit-form').onsubmit=e=>{e.preventDefault();try{const o=objects.find(o=>o.id===dialogPoint);commit({...o,name:$('dialog-name').value.trim(),coords:[0,1,2].map(i=>i<dimension?$('dialog-'+i).value:'0')});$('point-dialog').close();form();}catch(err){$('dialog-error').textContent=err.message;}};$('close-dialog').onclick=()=>$('point-dialog').close();
$('selection-color').onchange=()=>{const o=objects.find(o=>o.id===selected),value=$('selection-color').value;if(!o||!/^#[0-9a-f]{6}$/i.test(value))return;remember();if(selectedEdge!==null)o.edgeColors={...o.edgeColors,[selectedEdge]:value};else o.color=value;refresh();};
$('edit-selected').onclick=()=>editObject(selected);$('clear-selection').onclick=()=>{selected=null;selectedEdge=null;selectionUI();draw();};
$('example').onclick=()=>{remember();preset($('preset').value);};$('undo').onclick=undoAction;$('redo').onclick=redoAction;$('restart').onclick=()=>{remember();preset('empty');$('status').textContent='Đã bắt đầu bản vẽ trống. Bấm mũi tên quay lại hoặc Ctrl+Z để khôi phục.';};$('fit').onclick=fit;
for(const k of [...displayKeys,'snap-step'])$(k).onchange=()=>{draw();persist();};$('notes').oninput=persist;$('auto-build').onchange=()=>{updateSteps();persist();maybeAutoBuild();};
$('save').onclick=()=>download(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),'curvelab-dung-hinh-'+dimension+'d.json');$('png').onclick=()=>canvas.toBlob(b=>{if(b)download(b,'curvelab-'+dimension+'d.png');});$('load').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>500000)throw Error('Tệp quá lớn (tối đa 500 KB).');const d=G.importDocument(JSON.parse(await f.text()));remember();restore(d);}catch(err){$('error').textContent=err.message;}e.target.value='';};
document.addEventListener('focusin',e=>{if(e.target.matches('[data-math]'))lastInput=e.target;});for(const [label,value] of [['a/b','()/()'],['x²','()^2'],['√','sqrt()'],['π','pi'],['sin','sin()'],['cos','cos()']]){const b=el('button',label);b.type='button';b.onmousedown=e=>e.preventDefault();b.onclick=()=>{const input=lastInput&&lastInput.isConnected?lastInput:document.querySelector('[data-math]');if(!input)return;const start=input.selectionStart??input.value.length,end=input.selectionEnd??start,selected=input.value.slice(start,end),s=selected?value.replace('()', '('+selected+')'):value;input.setRangeText(s,start,end,'end');input.focus();const pos=s.indexOf('()');if(pos>=0)input.setSelectionRange(start+pos+1,start+pos+1);};$('keys').append(b);}
function setView(name){const a={iso:[.65,-.65],xy:[0,0],xz:[0,-Math.PI/2],yz:[Math.PI/2,-Math.PI/2]}[name];[view.yaw,view.pitch]=a;view.plane=name;if(name!=='iso'){$('placement-plane').value=name;$('level-label').textContent={xy:'z =',xz:'y =',yz:'x ='}[name];}document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.view===name)));draw();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('placement-plane').onchange=()=>{$('level-label').textContent={xy:'z =',xz:'y =',yz:'x ='}[$('placement-plane').value];};
canvas.onwheel=e=>{e.preventDefault();view.scale=Math.max(.000001,Math.min(1e7,view.scale*Math.exp(-Math.max(-200,Math.min(200,e.deltaY))*.0015)));draw();};
canvas.onpointerdown=e=>{if(e.button!==0)return;const p=local(e),label=hitLabel(p);if(label){const o=objects.find(o=>o.id===label.id);drag={x:e.clientX,y:e.clientY,label:o,offset:[...labelOffset(o)],started:false};canvas.setPointerCapture(e.pointerId);return;}const hit=hitAt(p,true),o=objects.find(o=>o.id===hit);drag={x:e.clientX,y:e.clientY,view:{...view},hit:$('tool').value==='select'&&o?.kind==='point'?o:null,original:o?.kind==='point'?resolved.get(o.id).p.slice():null,started:false,shift:e.shiftKey};canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{const p=local(e);try{$('cursor-coordinate').textContent='('+mousePoint(p).slice(0,dimension).map(fmt).join('; ')+')'+(checked('snap')?' · làm tròn theo bước '+$('snap-step').value:'');}catch{$('cursor-coordinate').textContent='Chọn mặt phẳng đặt điểm phù hợp với góc nhìn.';}if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(!drag.started&&Math.hypot(dx,dy)<4)return;try{if(drag.label){if(!drag.started)remember();const offset=[drag.offset[0]+dx,drag.offset[1]+dy],length=Math.hypot(...offset);drag.label.labelOffset=length>LABEL_RADIUS?offset.map(v=>v*LABEL_RADIUS/length):offset;selected=drag.label.id;selectedEdge=null;selectionUI();draw();}else if(drag.hit){const q=mousePoint(p,drag.original);if(!drag.started)remember();drag.hit.coords=q.map(String);selected=drag.hit.id;selectedEdge=null;refresh();}else if(dimension===3&&!drag.shift){view.yaw=drag.view.yaw+dx*.008;view.pitch=drag.view.pitch+dy*.008;view.plane='iso';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed','false'));draw();}else if(dimension===3){const a=drag.view.yaw,b=drag.view.pitch,shift=G.add(G.mul([Math.cos(a),-Math.sin(a),0],-dx/view.scale),G.mul([Math.cos(b)*Math.sin(a),Math.cos(b)*Math.cos(a),-Math.sin(b)],dy/view.scale));[view.x,view.y,view.z]=G.add([drag.view.x,drag.view.y,drag.view.z],shift);draw();}else{view.x=drag.view.x-dx/view.scale;view.y=drag.view.y+dy/view.scale;draw();}drag.started=true;}catch(err){$('error').textContent=err.message;drag.started=true;}};
canvas.onpointerup=e=>{if(!drag)return;const click=!drag.started,label=drag.label;drag=null;if(label){if(click)chooseObject(label.id);else persist();return;}if(click)try{canvasClick(local(e));}catch(err){$('error').textContent=err.message;}};canvas.onpointercancel=()=>{if(drag?.label&&drag.started)persist();drag=null;};canvas.ondblclick=e=>{e.preventDefault();const label=hitLabel(local(e));if(label){remember();delete objects.find(o=>o.id===label.id).labelOffset;refresh();return;}const hit=hitAt(local(e),true);if(hit)editObject(hit);};canvas.onkeydown=e=>{if(e.key==='Escape')setTool('select');if(e.key==='Enter'&&selected)editObject(selected);};
document.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey)||e.altKey)return;const target=e.target;if(target?.matches?.('textarea,input:not([type=checkbox],[type=range],[type=button],[type=submit],[type=file],[type=color]),[contenteditable="true"]'))return;const key=e.key.toLowerCase();if(key==='z'||key==='y'){e.preventDefault();if(key==='y'||e.shiftKey)redoAction();else undoAction();}});
window.addEventListener('hashchange',()=>{persist();dimension=location.hash==='#space'?3:2;history=[];future=[];modeUI();try{const d=localStorage.getItem('curvelab-construction-'+dimension);if(d){restore(JSON.parse(d));return;}}catch{}preset(dimension===2?'triangle':'tetrahedron');});
modeUI();$('snap-step').value='0.25';$('placement-plane').value='xy';setTool('select');resize();try{const d=localStorage.getItem('curvelab-construction-'+dimension);if(d)restore(JSON.parse(d));else{const legacy=dimension===2?localStorage.getItem('curvelab-studio-v1'):null,old=legacy?JSON.parse(legacy):null;if(old?.mode==='geometry')restore(old);else preset(dimension===2?'triangle':'tetrahedron');}}catch{preset(dimension===2?'triangle':'tetrahedron');}new ResizeObserver(resize).observe(canvas);
function exportLatex(){if(!objects.length)throw Error('Chưa có đối tượng để xuất.');const native=ctx,rec=new CurveTikZ.Recorder(W,H,native);try{rec.objectsOnly=true;ctx=rec;draw();}finally{ctx=native;}const points=objects.map(o=>({o,q:resolved.get(o.id)})).filter(({q})=>q?.type==='point'&&!q.error).map(({o,q})=>({name:o.name,world:q.p,screen:project(q.p)}));return rec.document({title:dimension===2?'Hinh hoc phang':'Hinh hoc khong gian',points});}
$('latex-export').onclick=()=>{try{CurveTikZ.download(exportLatex(),'curvelab-'+dimension+'d.tex');$('status').textContent='Đã xuất TikZ theo hình hiện tại. Biên dịch tệp .tex bằng XeLaTeX.';}catch(e){$('error').textContent='Không xuất được LaTeX: '+e.message;}};
window.ConstructionApp={exportLatex,get objects(){return objects;},get resolved(){return resolved;},get dimension(){return dimension;},get view(){return {...view};},get selected(){return selected;},get selectedEdge(){return selectedEdge;},get markCount(){return markCount;},snapshot,restore,quickPoints,project,setTool,setView};

$('png').objectExport=()=>{const native=ctx,out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const target=out.getContext('2d');target.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);target.objectsOnly=true;try{ctx=target;draw();}finally{ctx=native;draw();}out.toBlob(b=>b&&download(b,'curvelab-doi-tuong.png'));};
})();
